using System.Text;
using Dispatcher.SourceGeneration.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Dispatcher.SourceGeneration.Emission;

internal static class GeneratedDispatcherEmitter
{
    internal static void Emit(SourceProductionContext context, GenerationResult result)
    {
        const string className = "Dispatcher";
        const string generatedNamespace = "Dispatcher";
        var generatedTypeName = "global::" + generatedNamespace + "." + className;
        var queries = result.DispatchRoutes.Where(route => route.Handler?.Kind == HandlerModelKind.Query).ToArray();
        var responseCommands = result.DispatchRoutes
            .Where(route => route.Handler?.Kind == HandlerModelKind.CommandWithResponse)
            .ToArray();
        var commands = result.DispatchRoutes
            .Where(route => route.Handler?.Kind == HandlerModelKind.Command)
            .ToArray();
        var notifications = result.DispatchRoutes
            .Where(route => route.Handler?.Kind == HandlerModelKind.Notification ||
                !route.OpenNotificationHandlers.IsDefaultOrEmpty)
            .ToArray();
        var hasOpenNotificationHandlers = !result.DispatchOpenNotificationHandlers.IsDefaultOrEmpty;
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using global::System.Collections.Frozen;");
        source.AppendLine();
        source.Append("namespace ").Append(generatedNamespace).AppendLine(";");
        source.AppendLine();
        source.Append("internal sealed class ").Append(className).AppendLine(" : global::Dispatcher.IDispatcher");
        source.AppendLine("{");
        source.AppendLine("    private readonly global::System.IServiceProvider serviceProvider;");
        if (hasOpenNotificationHandlers)
        {
            source.AppendLine("    private readonly global::Dispatcher.OpenNotificationHandlerRegistry openNotificationHandlers;");
        }
        AppendRequestDictionary(source, generatedTypeName, "QueryHandlers", queries, "global::Dispatcher.IQuery", "QueryCore");
        AppendRequestDictionary(source, generatedTypeName, "ResponseCommandHandlers", responseCommands, "global::Dispatcher.ICommand", "ResponseCommandCore");
        AppendCommandDictionary(source, generatedTypeName, commands);
        AppendNotificationDictionary(source, generatedTypeName, notifications);
        source.AppendLine();
        source.Append("    public ").Append(className).AppendLine("(");
        source.Append("        global::System.IServiceProvider serviceProvider")
            .AppendLine(hasOpenNotificationHandlers ? "," : ")");
        if (hasOpenNotificationHandlers)
        {
            source.AppendLine("        global::Dispatcher.OpenNotificationHandlerRegistry openNotificationHandlers)");
        }
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(serviceProvider);");
        source.AppendLine("        this.serviceProvider = serviceProvider;");
        if (hasOpenNotificationHandlers)
        {
            source.AppendLine("        this.openNotificationHandlers = openNotificationHandlers;");
        }
        source.AppendLine("    }");
        AppendDispatcherMethods(source, generatedTypeName);
        AppendCoreMethods(source, hasOpenNotificationHandlers);
        AppendRouteAvailabilityMethods(source);
        source.AppendLine("}");
        if (hasOpenNotificationHandlers)
        {
            AppendOpenNotificationHandlerRegistry(source, notifications, result.DispatchOpenNotificationHandlers);
        }
        GeneratedTelemetryEmitter.Append(
            source,
            generatedTypeName,
            queries,
            responseCommands,
            commands,
            notifications);
        context.AddSource(className + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));

        const string extensionsName = "GeneratedDispatcherServiceCollectionExtensions";
        var registration = new StringBuilder();
        registration.AppendLine("// <auto-generated />");
        registration.AppendLine("#nullable enable");
        registration.AppendLine();
        registration.AppendLine("namespace Dispatcher.SourceGeneration;");
        registration.AppendLine();
        registration.AppendLine("/// <summary>");
        registration.AppendLine("/// Provides registration methods for the source-generated Dispatcher implementation.");
        registration.AppendLine("/// </summary>");
        registration.Append("public static class ").Append(extensionsName).AppendLine();
        registration.AppendLine("{");
        registration.AppendLine("    /// <summary>");
        registration.AppendLine("    /// Registers the source-generated Dispatcher implementation.");
        registration.AppendLine("    /// </summary>");
        registration.AppendLine("    /// <param name=\"services\">The service collection to add Dispatcher services to.</param>");
        registration.AppendLine("    /// <returns>The same service collection so that additional calls can be chained.</returns>");
        registration.AppendLine("    /// <exception cref=\"global::System.ArgumentNullException\">");
        registration.AppendLine("    /// <paramref name=\"services\"/> is <see langword=\"null\"/>.");
        registration.AppendLine("    /// </exception>");
        registration.Append("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection ")
            .Append(result.DispatcherMethodName).AppendLine("(");
        registration.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        registration.Append("        => ").Append(result.DispatcherMethodName)
            .AppendLine("(services, static _ => { });");
        registration.AppendLine();
        registration.AppendLine("    /// <summary>");
        registration.AppendLine("    /// Registers the source-generated Dispatcher implementation using the specified options.");
        registration.AppendLine("    /// </summary>");
        registration.AppendLine("    /// <param name=\"services\">The service collection to add Dispatcher services to.</param>");
        registration.AppendLine("    /// <param name=\"configure\">The delegate that configures Dispatcher services.</param>");
        registration.AppendLine("    /// <returns>The same service collection so that additional calls can be chained.</returns>");
        registration.AppendLine("    /// <exception cref=\"global::System.ArgumentNullException\">");
        registration.AppendLine("    /// <paramref name=\"services\"/> or <paramref name=\"configure\"/> is <see langword=\"null\"/>.");
        registration.AppendLine("    /// </exception>");
        registration.AppendLine("    /// <exception cref=\"global::System.ArgumentOutOfRangeException\">");
        registration.AppendLine("    /// <paramref name=\"configure\"/> sets the Dispatcher service lifetime to singleton.");
        registration.AppendLine("    /// </exception>");
        registration.Append("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection ")
            .Append(result.DispatcherMethodName).AppendLine("(");
        registration.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        registration.AppendLine("        global::System.Action<global::Dispatcher.DispatcherOptions> configure)");
        registration.AppendLine("    {");
        registration.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(services);");
        registration.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(configure);");
        registration.AppendLine("        var options = new global::Dispatcher.DispatcherOptions();");
        registration.AppendLine("        configure(options);");
        registration.AppendLine("        if (options.ServiceLifetime == global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton)");
        registration.AppendLine("        {");
        registration.AppendLine("            throw new global::System.ArgumentOutOfRangeException(");
        registration.AppendLine("                nameof(configure),");
        registration.AppendLine("                options.ServiceLifetime,");
        registration.AppendLine("                \"A singleton dispatcher would capture the root service provider.\");");
        registration.AppendLine("        }");
        registration.AppendLine();
        registration.AppendLine("        foreach (var descriptor in services)");
        registration.AppendLine("        {");
        registration.Append("            if (descriptor.ServiceType == typeof(").Append(generatedTypeName).AppendLine("))");
        registration.AppendLine("            {");
        registration.AppendLine("                return services;");
        registration.AppendLine("            }");
        registration.AppendLine("        }");
        registration.AppendLine();
        if (hasOpenNotificationHandlers)
        {
            registration.AppendLine("        services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton(");
            registration.AppendLine("            typeof(global::Dispatcher.OpenNotificationHandlerRegistry),");
            registration.AppendLine("            typeof(global::Dispatcher.OpenNotificationHandlerRegistry)));");
        }
        registration.Append("        services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(typeof(")
            .Append(generatedTypeName).Append("), typeof(").Append(generatedTypeName)
            .AppendLine("), options.ServiceLifetime));");
        registration.AppendLine("        var telemetry = options.Telemetry;");
        registration.AppendLine("        if (telemetry.EnableMetrics || telemetry.EnableTracing)");
        registration.AppendLine("        {");
        registration.AppendLine("            var enableMetrics = telemetry.EnableMetrics;");
        registration.AppendLine("            var enableTracing = telemetry.EnableTracing;");
        registration.AppendLine("            var meterName = telemetry.MeterName;");
        registration.AppendLine("            var activitySourceName = telemetry.ActivitySourceName;");
        registration.AppendLine("            services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton(");
        registration.AppendLine("                typeof(global::Dispatcher.DispatcherTelemetry),");
        registration.AppendLine("                _ => new global::Dispatcher.DispatcherTelemetry(");
        registration.AppendLine("                    enableMetrics,");
        registration.AppendLine("                    enableTracing,");
        registration.AppendLine("                    meterName,");
        registration.AppendLine("                    activitySourceName)));");
        registration.AppendLine("            services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(");
        registration.AppendLine("                typeof(global::Dispatcher.TelemetryDispatcher),");
        registration.AppendLine("                typeof(global::Dispatcher.TelemetryDispatcher),");
        registration.AppendLine("                options.ServiceLifetime));");
        AppendDispatcherContractRegistration(
            registration,
            "global::Dispatcher.IDispatcher",
            "global::Dispatcher.TelemetryDispatcher",
            12);
        AppendDispatcherContractRegistration(
            registration,
            "global::Dispatcher.IQueryDispatcher",
            "global::Dispatcher.TelemetryDispatcher",
            12);
        AppendDispatcherContractRegistration(
            registration,
            "global::Dispatcher.ICommandDispatcher",
            "global::Dispatcher.TelemetryDispatcher",
            12);
        AppendDispatcherContractRegistration(
            registration,
            "global::Dispatcher.INotificationDispatcher",
            "global::Dispatcher.TelemetryDispatcher",
            12);
        registration.AppendLine("        }");
        registration.AppendLine("        else");
        registration.AppendLine("        {");
        AppendDispatcherContractRegistration(registration, "global::Dispatcher.IDispatcher", generatedTypeName, 12);
        AppendDispatcherContractRegistration(registration, "global::Dispatcher.IQueryDispatcher", generatedTypeName, 12);
        AppendDispatcherContractRegistration(registration, "global::Dispatcher.ICommandDispatcher", generatedTypeName, 12);
        AppendDispatcherContractRegistration(registration, "global::Dispatcher.INotificationDispatcher", generatedTypeName, 12);
        registration.AppendLine("        }");
        registration.AppendLine();
        registration.AppendLine("        return services;");
        registration.AppendLine("    }");
        registration.AppendLine("}");
        context.AddSource(extensionsName + ".g.cs", SourceText.From(registration.ToString(), Encoding.UTF8));

    }

    private static void AppendRequestDictionary(
        StringBuilder source,
        string generatedTypeName,
        string fieldName,
        IEnumerable<DispatchRouteModel> routes,
        string messageInterface,
        string coreMethod)
    {
        source.AppendLine();
        source.Append("    private static readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type, (global::System.Type ResponseType, object Handler)> ")
            .Append(fieldName).AppendLine(" =");
        source.AppendLine("        new global::System.Collections.Generic.Dictionary<global::System.Type, (global::System.Type ResponseType, object Handler)>");
        source.AppendLine("        {");
        foreach (var route in routes)
        {
            var message = route.MessageType.ToDisplayString(SymbolDisplayFormats.FullyQualified);
            var handledMessage = route.Handler!.MessageType.ToDisplayString(SymbolDisplayFormats.FullyQualified);
            var response = route.Handler.ResponseType!.ToDisplayString(SymbolDisplayFormats.FullyQualified);
            source.Append("            [typeof(").Append(message).Append(")] = (typeof(").Append(response)
                .Append("), (global::System.Func<")
                .Append(generatedTypeName)
                .Append(", ").Append(messageInterface).Append('<').Append(response)
                .Append(">, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask<")
                .Append(response).Append(">>)(").AppendLine();
            source.Append("                static (dispatcher, message, token) => dispatcher.")
                .Append(coreMethod).Append("<").Append(handledMessage).Append(", ").Append(response)
                .Append(">((").Append(handledMessage).AppendLine(")message, token))),");
        }
        source.AppendLine("        }.ToFrozenDictionary();");
    }

    private static void AppendCommandDictionary(
        StringBuilder source,
        string generatedTypeName,
        IEnumerable<DispatchRouteModel> routes)
    {
        source.AppendLine();
        source.AppendLine("    private static readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type,");
        source.Append("        global::System.Func<").Append(generatedTypeName)
            .AppendLine(", global::Dispatcher.ICommand, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask>> CommandHandlers =");
        source.AppendLine("        new global::System.Collections.Generic.Dictionary<global::System.Type,");
        source.Append("            global::System.Func<").Append(generatedTypeName)
            .AppendLine(", global::Dispatcher.ICommand, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask>>");
        source.AppendLine("        {");
        foreach (var route in routes)
        {
            var message = route.MessageType.ToDisplayString(SymbolDisplayFormats.FullyQualified);
            var handledMessage = route.Handler!.MessageType.ToDisplayString(SymbolDisplayFormats.FullyQualified);
            source.Append("            [typeof(").Append(message).Append(")] = static (dispatcher, command, token) => dispatcher.CommandCore<")
                .Append(handledMessage).Append(">((").Append(handledMessage).AppendLine(")command, token),");
        }
        source.AppendLine("        }.ToFrozenDictionary();");
    }

    private static void AppendNotificationDictionary(
        StringBuilder source,
        string generatedTypeName,
        IEnumerable<DispatchRouteModel> routes)
    {
        source.AppendLine();
        source.AppendLine("    private static readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type,");
        source.Append("        global::System.Func<").Append(generatedTypeName)
            .AppendLine(", global::Dispatcher.INotification, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask>> NotificationHandlers =");
        source.AppendLine("        new global::System.Collections.Generic.Dictionary<global::System.Type,");
        source.Append("            global::System.Func<").Append(generatedTypeName)
            .AppendLine(", global::Dispatcher.INotification, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask>>");
        source.AppendLine("        {");
        foreach (var route in routes)
        {
            var message = route.MessageType.ToDisplayString(SymbolDisplayFormats.FullyQualified);
            if (route.Handler is null)
            {
                source.Append("            [typeof(").Append(message)
                    .Append(")] = static (dispatcher, notification, token) => dispatcher.OpenNotificationCore<")
                    .Append(message).Append(">((").Append(message).AppendLine(")notification, token),");
                continue;
            }

            var handledMessage = route.Handler.MessageType.ToDisplayString(SymbolDisplayFormats.FullyQualified);
            if (route.OpenNotificationHandlers.IsDefaultOrEmpty)
            {
                source.Append("            [typeof(").Append(message).Append(")] = static (dispatcher, notification, token) => dispatcher.NotificationCore<")
                    .Append(handledMessage).Append(">((").Append(handledMessage).AppendLine(")notification, token),");
                continue;
            }

            source.Append("            [typeof(").Append(message).Append(")] = static (dispatcher, notification, token) => dispatcher.NotificationCore<")
                .Append(handledMessage).Append(", ").Append(message).Append(">((")
                .Append(handledMessage).Append(")notification, (").Append(message)
                .AppendLine(")notification, token),");
        }
        source.AppendLine("        }.ToFrozenDictionary();");
    }

    private static void AppendDispatcherMethods(StringBuilder source, string generatedTypeName)
    {
        source.AppendLine();
        source.AppendLine("    public global::System.Threading.Tasks.ValueTask<TResponse> QueryAsync<TResponse>(");
        source.AppendLine("        global::Dispatcher.IQuery<TResponse> query,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(query);");
        source.AppendLine("        if (!QueryHandlers.TryGetValue(query.GetType(), out var entry))");
        source.AppendLine("        {");
        source.AppendLine("            throw new global::Dispatcher.HandlerNotFoundException(query.GetType());");
        source.AppendLine("        }");
        source.AppendLine("        if (entry.ResponseType != typeof(TResponse))");
        source.AppendLine("        {");
        source.AppendLine("            throw new global::System.InvalidOperationException($\"The generated handler shape does not match message type '{query.GetType().FullName}'.\");");
        source.AppendLine("        }");
        source.Append("        return global::System.Runtime.CompilerServices.Unsafe.As<global::System.Func<")
            .Append(generatedTypeName).AppendLine(", global::Dispatcher.IQuery<TResponse>, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask<TResponse>>>(entry.Handler)(this, query, cancellationToken);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public global::System.Threading.Tasks.ValueTask<TResponse> ExecuteAsync<TResponse>(");
        source.AppendLine("        global::Dispatcher.ICommand<TResponse> command,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(command);");
        source.AppendLine("        if (!ResponseCommandHandlers.TryGetValue(command.GetType(), out var entry))");
        source.AppendLine("        {");
        source.AppendLine("            throw new global::Dispatcher.HandlerNotFoundException(command.GetType());");
        source.AppendLine("        }");
        source.AppendLine("        if (entry.ResponseType != typeof(TResponse))");
        source.AppendLine("        {");
        source.AppendLine("            throw new global::System.InvalidOperationException($\"The generated handler shape does not match message type '{command.GetType().FullName}'.\");");
        source.AppendLine("        }");
        source.Append("        return global::System.Runtime.CompilerServices.Unsafe.As<global::System.Func<")
            .Append(generatedTypeName).AppendLine(", global::Dispatcher.ICommand<TResponse>, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask<TResponse>>>(entry.Handler)(this, command, cancellationToken);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public global::System.Threading.Tasks.ValueTask ExecuteAsync(");
        source.AppendLine("        global::Dispatcher.ICommand command,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(command);");
        source.AppendLine("        return CommandHandlers.TryGetValue(command.GetType(), out var handler)");
        source.AppendLine("            ? handler(this, command, cancellationToken)");
        source.AppendLine("            : global::System.Threading.Tasks.ValueTask.FromException(");
        source.AppendLine("                new global::Dispatcher.HandlerNotFoundException(command.GetType()));");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public global::System.Threading.Tasks.ValueTask PublishAsync<TNotification>(");
        source.AppendLine("        TNotification notification,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        source.AppendLine("        where TNotification : global::Dispatcher.INotification");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(notification);");
        source.AppendLine("        return NotificationHandlers.TryGetValue(notification.GetType(), out var handler)");
        source.AppendLine("            ? handler(this, notification, cancellationToken)");
        source.AppendLine("            : global::System.Threading.Tasks.ValueTask.CompletedTask;");
        source.AppendLine("    }");
    }

    private static void AppendCoreMethods(StringBuilder source, bool hasOpenNotificationHandlers)
    {
        source.AppendLine();
        source.AppendLine("    private global::System.Threading.Tasks.ValueTask<TResponse> QueryCore<TQuery, TResponse>(");
        source.AppendLine("        TQuery query, global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TQuery : global::Dispatcher.IQuery<TResponse> =>");
        source.AppendLine("        RequestCore<TQuery, TResponse>(query, GetRequiredService<global::Dispatcher.IQueryHandler<TQuery, TResponse>>(), cancellationToken);");
        source.AppendLine();
        source.AppendLine("    private global::System.Threading.Tasks.ValueTask<TResponse> ResponseCommandCore<TCommand, TResponse>(");
        source.AppendLine("        TCommand command, global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TCommand : global::Dispatcher.ICommand<TResponse> =>");
        source.AppendLine("        RequestCore<TCommand, TResponse>(command, GetRequiredService<global::Dispatcher.ICommandHandler<TCommand, TResponse>>(), cancellationToken);");
        source.AppendLine();
        source.AppendLine("    private global::System.Threading.Tasks.ValueTask<TResponse> RequestCore<TRequest, TResponse>(");
        source.AppendLine("        TRequest request,");
        source.AppendLine("        global::Dispatcher.IQueryHandler<TRequest, TResponse> handler,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TRequest : global::Dispatcher.IQuery<TResponse>");
        source.AppendLine("    {");
        source.AppendLine("        var behaviors = GetServices<global::Dispatcher.IPipelineBehavior<TRequest, TResponse>>();");
        source.AppendLine("        if (behaviors.Count == 0)");
        source.AppendLine("        {");
        source.AppendLine("            return handler.HandleAsync(request, cancellationToken);");
        source.AppendLine("        }");
        source.AppendLine("        return RunQueryPipeline(request, handler, behaviors, cancellationToken);");
        source.AppendLine("    }");
        if (hasOpenNotificationHandlers)
        {
            source.AppendLine();
            source.AppendLine("    private async global::System.Threading.Tasks.ValueTask NotificationCore<THandledNotification, TNotification>(");
            source.AppendLine("        THandledNotification handledNotification,");
            source.AppendLine("        TNotification notification,");
            source.AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
            source.AppendLine("        where THandledNotification : global::Dispatcher.INotification");
            source.AppendLine("        where TNotification : global::Dispatcher.INotification");
            source.AppendLine("    {");
            source.AppendLine("        var handlers = GetServices<global::Dispatcher.INotificationHandler<THandledNotification>>();");
            source.AppendLine("        for (var index = 0; index < handlers.Count; index++)");
            source.AppendLine("        {");
            source.AppendLine("            await handlers[index].HandleAsync(handledNotification, cancellationToken).ConfigureAwait(false);");
            source.AppendLine("        }");
            source.AppendLine("        await OpenNotificationCore(notification, cancellationToken).ConfigureAwait(false);");
            source.AppendLine("    }");
            source.AppendLine();
            source.AppendLine("    private async global::System.Threading.Tasks.ValueTask OpenNotificationCore<TNotification>(");
            source.AppendLine("        TNotification notification, global::System.Threading.CancellationToken cancellationToken)");
            source.AppendLine("        where TNotification : global::Dispatcher.INotification");
            source.AppendLine("    {");
            source.AppendLine("        var handlers = openNotificationHandlers.GetHandlers(typeof(TNotification));");
            source.AppendLine("        for (var index = 0; index < handlers.Length; index++)");
            source.AppendLine("        {");
            source.AppendLine("            await handlers[index](serviceProvider, notification, cancellationToken).ConfigureAwait(false);");
            source.AppendLine("        }");
            source.AppendLine("    }");
        }
        source.AppendLine();
        source.AppendLine("    private global::System.Threading.Tasks.ValueTask<TResponse> RequestCore<TRequest, TResponse>(");
        source.AppendLine("        TRequest request,");
        source.AppendLine("        global::Dispatcher.ICommandHandler<TRequest, TResponse> handler,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TRequest : global::Dispatcher.ICommand<TResponse>");
        source.AppendLine("    {");
        source.AppendLine("        var behaviors = GetServices<global::Dispatcher.IPipelineBehavior<TRequest, TResponse>>();");
        source.AppendLine("        if (behaviors.Count == 0)");
        source.AppendLine("        {");
        source.AppendLine("            return handler.HandleAsync(request, cancellationToken);");
        source.AppendLine("        }");
        source.AppendLine("        return RunResponseCommandPipeline(request, handler, behaviors, cancellationToken);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static global::System.Threading.Tasks.ValueTask<TResponse> RunQueryPipeline<TRequest, TResponse>(");
        source.AppendLine("        TRequest request,");
        source.AppendLine("        global::Dispatcher.IQueryHandler<TRequest, TResponse> handler,");
        source.AppendLine("        global::System.Collections.Generic.IReadOnlyList<global::Dispatcher.IPipelineBehavior<TRequest, TResponse>> behaviors,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TRequest : global::Dispatcher.IQuery<TResponse>");
        source.AppendLine("    {");
        AppendPipelineBody(source, "request", "handler.HandleAsync(request, token)");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static global::System.Threading.Tasks.ValueTask<TResponse> RunResponseCommandPipeline<TRequest, TResponse>(");
        source.AppendLine("        TRequest request,");
        source.AppendLine("        global::Dispatcher.ICommandHandler<TRequest, TResponse> handler,");
        source.AppendLine("        global::System.Collections.Generic.IReadOnlyList<global::Dispatcher.IPipelineBehavior<TRequest, TResponse>> behaviors,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TRequest : global::Dispatcher.ICommand<TResponse>");
        source.AppendLine("    {");
        AppendPipelineBody(source, "request", "handler.HandleAsync(request, token)");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private global::System.Threading.Tasks.ValueTask CommandCore<TCommand>(");
        source.AppendLine("        TCommand command, global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TCommand : global::Dispatcher.ICommand");
        source.AppendLine("    {");
        source.AppendLine("        var handler = GetRequiredService<global::Dispatcher.ICommandHandler<TCommand>>();");
        source.AppendLine("        var behaviors = GetServices<global::Dispatcher.IPipelineBehavior<TCommand, global::Dispatcher.Unit>>();");
        source.AppendLine("        if (behaviors.Count == 0)");
        source.AppendLine("        {");
        source.AppendLine("            return handler.HandleAsync(command, cancellationToken);");
        source.AppendLine("        }");
        source.AppendLine("        return RunCommandPipeline(command, handler, behaviors, cancellationToken);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static async global::System.Threading.Tasks.ValueTask RunCommandPipeline<TCommand>(");
        source.AppendLine("        TCommand command,");
        source.AppendLine("        global::Dispatcher.ICommandHandler<TCommand> handler,");
        source.AppendLine("        global::System.Collections.Generic.IReadOnlyList<global::Dispatcher.IPipelineBehavior<TCommand, global::Dispatcher.Unit>> behaviors,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TCommand : global::Dispatcher.ICommand");
        source.AppendLine("    {");
        source.AppendLine("        global::Dispatcher.RequestHandlerDelegate<global::Dispatcher.Unit> pipeline = async token =>");
        source.AppendLine("        {");
        source.AppendLine("            await handler.HandleAsync(command, token).ConfigureAwait(false);");
        source.AppendLine("            return global::Dispatcher.Unit.Value;");
        source.AppendLine("        };");
        source.AppendLine("        for (var index = behaviors.Count - 1; index >= 1; index--)");
        source.AppendLine("        {");
        source.AppendLine("            var behavior = behaviors[index];");
        source.AppendLine("            var next = pipeline;");
        source.AppendLine("            pipeline = token => behavior.HandleAsync(command, next, token);");
        source.AppendLine("        }");
        source.AppendLine("        await behaviors[0].HandleAsync(command, pipeline, cancellationToken).ConfigureAwait(false);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private async global::System.Threading.Tasks.ValueTask NotificationCore<TNotification>(");
        source.AppendLine("        TNotification notification, global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TNotification : global::Dispatcher.INotification");
        source.AppendLine("    {");
        source.AppendLine("        var handlers = GetServices<global::Dispatcher.INotificationHandler<TNotification>>();");
        source.AppendLine("        for (var index = 0; index < handlers.Count; index++)");
        source.AppendLine("        {");
        source.AppendLine("            await handlers[index].HandleAsync(notification, cancellationToken).ConfigureAwait(false);");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private T GetRequiredService<T>() where T : notnull =>");
        source.AppendLine("        (T?)serviceProvider.GetService(typeof(T)) ??");
        source.AppendLine("        throw new global::System.InvalidOperationException($\"Service '{typeof(T).FullName}' is not registered.\");");
        source.AppendLine();
        source.AppendLine("    private global::System.Collections.Generic.IReadOnlyList<T> GetServices<T>()");
        source.AppendLine("    {");
        source.AppendLine("        var services = (global::System.Collections.Generic.IEnumerable<T>?)serviceProvider.GetService(");
        source.AppendLine("            typeof(global::System.Collections.Generic.IEnumerable<T>));");
        source.AppendLine("        return services switch");
        source.AppendLine("        {");
        source.AppendLine("            null => [],");
        source.AppendLine("            global::System.Collections.Generic.IReadOnlyList<T> list => list,");
        source.AppendLine("            _ => global::System.Linq.Enumerable.ToArray(services)");
        source.AppendLine("        };");
        source.AppendLine("    }");
    }

    private static void AppendRouteAvailabilityMethods(StringBuilder source)
    {
        source.AppendLine();
        source.AppendLine("    internal static bool HasQueryHandler(global::System.Type messageType, global::System.Type responseType) =>");
        source.AppendLine("        QueryHandlers.TryGetValue(messageType, out var entry) && entry.ResponseType == responseType;");
        source.AppendLine();
        source.AppendLine("    internal static bool HasResponseCommandHandler(global::System.Type messageType, global::System.Type responseType) =>");
        source.AppendLine("        ResponseCommandHandlers.TryGetValue(messageType, out var entry) && entry.ResponseType == responseType;");
        source.AppendLine();
        source.AppendLine("    internal static bool HasCommandHandler(global::System.Type messageType) =>");
        source.AppendLine("        CommandHandlers.ContainsKey(messageType);");
        source.AppendLine();
        source.AppendLine("    internal static bool HasNotificationHandlers(global::System.Type messageType) =>");
        source.AppendLine("        NotificationHandlers.ContainsKey(messageType);");
    }

    private static void AppendOpenNotificationHandlerRegistry(
        StringBuilder source,
        IReadOnlyList<DispatchRouteModel> notificationRoutes,
        IReadOnlyList<OpenGenericNotificationHandlerModel> openHandlers)
    {
        var openRoutes = notificationRoutes
            .Where(static route => !route.OpenNotificationHandlers.IsDefaultOrEmpty)
            .ToArray();
        source.AppendLine();
        source.AppendLine();
        source.AppendLine("internal delegate global::System.Threading.Tasks.ValueTask OpenNotificationHandlerInvoker(");
        source.AppendLine("    global::System.IServiceProvider serviceProvider,");
        source.AppendLine("    global::Dispatcher.INotification notification,");
        source.AppendLine("    global::System.Threading.CancellationToken cancellationToken);");
        source.AppendLine();
        source.AppendLine("internal sealed class OpenNotificationHandlerRegistry");
        source.AppendLine("{");
        source.AppendLine("    private readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type,");
        source.AppendLine("        global::Dispatcher.OpenNotificationHandlerInvoker[]> handlers;");
        source.AppendLine();
        source.AppendLine("    public OpenNotificationHandlerRegistry(");
        source.AppendLine("        global::System.Collections.Generic.IEnumerable<global::Dispatcher.HandlerRegistration> registrations)");
        source.AppendLine("    {");
        for (var routeIndex = 0; routeIndex < openRoutes.Length; routeIndex++)
        {
            source.Append("        var route").Append(routeIndex)
                .AppendLine(" = new global::System.Collections.Generic.List<global::Dispatcher.OpenNotificationHandlerInvoker>();");
        }

        source.AppendLine("        foreach (var registration in registrations)");
        source.AppendLine("        {");
        source.AppendLine("            if (registration is not global::Dispatcher.NotificationHandlerRegistration { IsOpenGeneric: true } notificationRegistration)");
        source.AppendLine("            {");
        source.AppendLine("                continue;");
        source.AppendLine("            }");
        foreach (var handler in openHandlers)
        {
            source.Append("            if (").Append(handler.RegistrationClassName)
                .Append(".IsOpenNotificationHandler_").Append(handler.MethodSuffix)
                .AppendLine("(notificationRegistration))");
            source.AppendLine("            {");
            for (var routeIndex = 0; routeIndex < openRoutes.Length; routeIndex++)
            {
                var route = openRoutes[routeIndex];
                if (!route.OpenNotificationHandlers.Any(candidate =>
                        SymbolEqualityComparer.Default.Equals(
                            candidate.ImplementationType,
                            handler.ImplementationType)))
                {
                    continue;
                }

                var message = route.MessageType.ToDisplayString(SymbolDisplayFormats.FullyQualified);
                source.Append("                route").Append(routeIndex)
                    .Append(".Add(static (provider, notification, token) => ")
                    .Append(handler.RegistrationClassName).Append(".InvokeOpenNotificationHandler_")
                    .Append(handler.MethodSuffix).Append('<').Append(message).Append(">(")
                    .Append("provider, (").Append(message).AppendLine(")notification, token));");
            }
            source.AppendLine("                continue;");
            source.AppendLine("            }");
        }
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        handlers = new global::System.Collections.Generic.Dictionary<global::System.Type,");
        source.AppendLine("            global::Dispatcher.OpenNotificationHandlerInvoker[]>");
        source.AppendLine("        {");
        for (var routeIndex = 0; routeIndex < openRoutes.Length; routeIndex++)
        {
            var message = openRoutes[routeIndex].MessageType
                .ToDisplayString(SymbolDisplayFormats.FullyQualified);
            source.Append("            [typeof(").Append(message).Append(")] = route")
                .Append(routeIndex).AppendLine(".ToArray(),");
        }
        source.AppendLine("        }.ToFrozenDictionary();");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    internal global::Dispatcher.OpenNotificationHandlerInvoker[] GetHandlers(");
        source.AppendLine("        global::System.Type notificationType) =>");
        source.AppendLine("        handlers.TryGetValue(notificationType, out var routeHandlers) ? routeHandlers : [];");
        source.AppendLine("}");
    }

    private static void AppendPipelineBody(StringBuilder source, string requestName, string handlerInvocation)
    {
        source.Append("        global::Dispatcher.RequestHandlerDelegate<TResponse> pipeline = token => ")
            .Append(handlerInvocation).AppendLine(";");
        source.AppendLine("        for (var index = behaviors.Count - 1; index >= 1; index--)");
        source.AppendLine("        {");
        source.AppendLine("            var behavior = behaviors[index];");
        source.AppendLine("            var next = pipeline;");
        source.Append("            pipeline = token => behavior.HandleAsync(").Append(requestName)
            .AppendLine(", next, token);");
        source.AppendLine("        }");
        source.Append("        return behaviors[0].HandleAsync(").Append(requestName)
            .AppendLine(", pipeline, cancellationToken);");
    }

    private static void AppendDispatcherContractRegistration(
        StringBuilder source,
        string contractType,
        string generatedTypeName,
        int indentation = 8)
    {
        var indent = new string(' ', indentation);
        source.Append(indent).Append("services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(")
            .Append(contractType).AppendLine("), static provider =>");
        source.Append(indent).Append("    provider.GetService(typeof(").Append(generatedTypeName).AppendLine(")) ??");
        source.Append(indent).Append("    throw new global::System.InvalidOperationException(\"Service '")
            .Append(generatedTypeName).AppendLine("' is not registered.\"), options.ServiceLifetime));");
    }
}