using System.Text;
using Dispatcher.SourceGeneration.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Dispatcher.SourceGeneration.Emission;

internal static class GeneratedDispatcherEmitter
{
    internal static void Emit(SourceProductionContext context, GenerationResult result)
    {
        const string className = "Dispatcher";
        const string generatedNamespace = "Dispatcher";
        var generatedTypeName = "global::" + generatedNamespace + "." + className;
        var queries = result.DispatchHandlers.Where(handler => handler.Kind == HandlerModelKind.Query).ToArray();
        var responseCommands = result.DispatchHandlers
            .Where(handler => handler.Kind == HandlerModelKind.CommandWithResponse)
            .ToArray();
        var commands = result.DispatchHandlers.Where(handler => handler.Kind == HandlerModelKind.Command).ToArray();
        var notifications = result.DispatchHandlers
            .Where(handler => handler.Kind == HandlerModelKind.Notification)
            .GroupBy(handler => handler.MessageType, SymbolEqualityComparer.Default)
            .Select(group => group.First())
            .ToArray();
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using global::System.Collections.Frozen;");
        source.AppendLine();
        source.Append("namespace ").Append(generatedNamespace).AppendLine(";");
        source.AppendLine();
        source.Append("internal sealed class ").Append(className).AppendLine(" : global::Dispatcher.IDispatcher");
        source.AppendLine("{");
        source.AppendLine("    private readonly global::System.IServiceProvider serviceProvider;");
        AppendRequestDictionary(source, generatedTypeName, "QueryHandlers", queries, "global::Dispatcher.IQuery", "QueryCore");
        AppendRequestDictionary(source, generatedTypeName, "ResponseCommandHandlers", responseCommands, "global::Dispatcher.ICommand", "ResponseCommandCore");
        AppendCommandDictionary(source, generatedTypeName, commands);
        AppendNotificationDictionary(source, generatedTypeName, notifications);
        source.AppendLine();
        source.Append("    public ").Append(className)
            .AppendLine("(global::System.IServiceProvider serviceProvider)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(serviceProvider);");
        source.AppendLine("        this.serviceProvider = serviceProvider;");
        source.AppendLine("    }");
        AppendDispatcherMethods(source, generatedTypeName);
        AppendCoreMethods(source);
        AppendRouteAvailabilityMethods(source);
        source.AppendLine("}");
        GeneratedTelemetryEmitter.Append(
            source,
            generatedTypeName,
            queries,
            responseCommands,
            commands,
            notifications);
        context.AddSource(className + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));

        const string extensionsName = "ServiceCollectionExtensions";
        var registration = new StringBuilder();
        registration.AppendLine("// <auto-generated />");
        registration.AppendLine("#nullable enable");
        registration.AppendLine();
        registration.AppendLine("namespace Dispatcher.SourceGeneration;");
        registration.AppendLine();
        registration.Append("public static class ").Append(extensionsName).AppendLine();
        registration.AppendLine("{");
        registration.Append("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection ")
            .Append(result.DispatcherMethodName).AppendLine("(");
        registration.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        registration.Append("        => ").Append(result.DispatcherMethodName)
            .AppendLine("(services, static _ => { });");
        registration.AppendLine();
        registration.Append("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection ")
            .Append(result.DispatcherMethodName).AppendLine("(");
        registration.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        registration.AppendLine("        global::System.Action<global::Dispatcher.DispatcherOptions> configure)");
        registration.AppendLine("    {");
        registration.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(services);");
        registration.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(configure);");
        registration.AppendLine("        var options = new global::Dispatcher.DispatcherOptions();");
        registration.AppendLine("        configure(options);");
        registration.AppendLine("        if (options.ServiceLifetime == global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton)");
        registration.AppendLine("        {");
        registration.AppendLine("            throw new global::System.ArgumentOutOfRangeException(");
        registration.AppendLine("                nameof(configure),");
        registration.AppendLine("                options.ServiceLifetime,");
        registration.AppendLine("                \"A singleton dispatcher would capture the root service provider.\");");
        registration.AppendLine("        }");
        registration.AppendLine();
        registration.AppendLine("        foreach (var descriptor in services)");
        registration.AppendLine("        {");
        registration.Append("            if (descriptor.ServiceType == typeof(").Append(generatedTypeName).AppendLine("))");
        registration.AppendLine("            {");
        registration.AppendLine("                return services;");
        registration.AppendLine("            }");
        registration.AppendLine("        }");
        registration.AppendLine();
        registration.Append("        services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(typeof(")
            .Append(generatedTypeName).Append("), typeof(").Append(generatedTypeName)
            .AppendLine("), options.ServiceLifetime));");
        registration.AppendLine("        var telemetry = options.Telemetry;");
        registration.AppendLine("        if (telemetry.EnableMetrics || telemetry.EnableTracing)");
        registration.AppendLine("        {");
        registration.AppendLine("            var enableMetrics = telemetry.EnableMetrics;");
        registration.AppendLine("            var enableTracing = telemetry.EnableTracing;");
        registration.AppendLine("            var meterName = telemetry.MeterName;");
        registration.AppendLine("            var activitySourceName = telemetry.ActivitySourceName;");
        registration.AppendLine("            services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton(");
        registration.AppendLine("                typeof(global::Dispatcher.DispatcherTelemetry),");
        registration.AppendLine("                _ => new global::Dispatcher.DispatcherTelemetry(");
        registration.AppendLine("                    enableMetrics,");
        registration.AppendLine("                    enableTracing,");
        registration.AppendLine("                    meterName,");
        registration.AppendLine("                    activitySourceName)));");
        registration.AppendLine("            services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(");
        registration.AppendLine("                typeof(global::Dispatcher.TelemetryDispatcher),");
        registration.AppendLine("                typeof(global::Dispatcher.TelemetryDispatcher),");
        registration.AppendLine("                options.ServiceLifetime));");
        AppendDispatcherContractRegistration(
            registration,
            "global::Dispatcher.IDispatcher",
            "global::Dispatcher.TelemetryDispatcher",
            12);
        AppendDispatcherContractRegistration(
            registration,
            "global::Dispatcher.IQueryDispatcher",
            "global::Dispatcher.TelemetryDispatcher",
            12);
        AppendDispatcherContractRegistration(
            registration,
            "global::Dispatcher.ICommandDispatcher",
            "global::Dispatcher.TelemetryDispatcher",
            12);
        AppendDispatcherContractRegistration(
            registration,
            "global::Dispatcher.INotificationDispatcher",
            "global::Dispatcher.TelemetryDispatcher",
            12);
        registration.AppendLine("        }");
        registration.AppendLine("        else");
        registration.AppendLine("        {");
        AppendDispatcherContractRegistration(registration, "global::Dispatcher.IDispatcher", generatedTypeName, 12);
        AppendDispatcherContractRegistration(registration, "global::Dispatcher.IQueryDispatcher", generatedTypeName, 12);
        AppendDispatcherContractRegistration(registration, "global::Dispatcher.ICommandDispatcher", generatedTypeName, 12);
        AppendDispatcherContractRegistration(registration, "global::Dispatcher.INotificationDispatcher", generatedTypeName, 12);
        registration.AppendLine("        }");
        registration.AppendLine();
        registration.AppendLine("        return services;");
        registration.AppendLine("    }");
        registration.AppendLine("}");
        context.AddSource(extensionsName + ".g.cs", SourceText.From(registration.ToString(), Encoding.UTF8));

    }

    private static void AppendRequestDictionary(
        StringBuilder source,
        string generatedTypeName,
        string fieldName,
        IEnumerable<HandlerModel> handlers,
        string messageInterface,
        string coreMethod)
    {
        source.AppendLine();
        source.Append("    private static readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type, (global::System.Type ResponseType, object Handler)> ")
            .Append(fieldName).AppendLine(" =");
        source.AppendLine("        new global::System.Collections.Generic.Dictionary<global::System.Type, (global::System.Type ResponseType, object Handler)>");
        source.AppendLine("        {");
        foreach (var handler in handlers)
        {
            var message = handler.MessageType.ToDisplayString(SymbolDisplayFormats.FullyQualified);
            var response = handler.ResponseType!.ToDisplayString(SymbolDisplayFormats.FullyQualified);
            source.Append("            [typeof(").Append(message).Append(")] = (typeof(").Append(response)
                .Append("), (global::System.Func<")
                .Append(generatedTypeName)
                .Append(", ").Append(messageInterface).Append('<').Append(response)
                .Append(">, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask<")
                .Append(response).Append(">>)(").AppendLine();
            source.Append("                static (dispatcher, message, token) => dispatcher.")
                .Append(coreMethod).Append("<").Append(message).Append(", ").Append(response)
                .Append(">((").Append(message).AppendLine(")message, token))),");
        }
        source.AppendLine("        }.ToFrozenDictionary();");
    }

    private static void AppendCommandDictionary(
        StringBuilder source,
        string generatedTypeName,
        IEnumerable<HandlerModel> handlers)
    {
        source.AppendLine();
        source.AppendLine("    private static readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type,");
        source.Append("        global::System.Func<").Append(generatedTypeName)
            .AppendLine(", global::Dispatcher.ICommand, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask>> CommandHandlers =");
        source.AppendLine("        new global::System.Collections.Generic.Dictionary<global::System.Type,");
        source.Append("            global::System.Func<").Append(generatedTypeName)
            .AppendLine(", global::Dispatcher.ICommand, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask>>");
        source.AppendLine("        {");
        foreach (var handler in handlers)
        {
            var message = handler.MessageType.ToDisplayString(SymbolDisplayFormats.FullyQualified);
            source.Append("            [typeof(").Append(message).Append(")] = static (dispatcher, command, token) => dispatcher.CommandCore<")
                .Append(message).Append(">((").Append(message).AppendLine(")command, token),");
        }
        source.AppendLine("        }.ToFrozenDictionary();");
    }

    private static void AppendNotificationDictionary(
        StringBuilder source,
        string generatedTypeName,
        IEnumerable<HandlerModel> handlers)
    {
        source.AppendLine();
        source.AppendLine("    private static readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type,");
        source.Append("        global::System.Func<").Append(generatedTypeName)
            .AppendLine(", global::Dispatcher.INotification, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask>> NotificationHandlers =");
        source.AppendLine("        new global::System.Collections.Generic.Dictionary<global::System.Type,");
        source.Append("            global::System.Func<").Append(generatedTypeName)
            .AppendLine(", global::Dispatcher.INotification, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask>>");
        source.AppendLine("        {");
        foreach (var handler in handlers)
        {
            var message = handler.MessageType.ToDisplayString(SymbolDisplayFormats.FullyQualified);
            source.Append("            [typeof(").Append(message).Append(")] = static (dispatcher, notification, token) => dispatcher.NotificationCore<")
                .Append(message).Append(">((").Append(message).AppendLine(")notification, token),");
        }
        source.AppendLine("        }.ToFrozenDictionary();");
    }

    private static void AppendDispatcherMethods(StringBuilder source, string generatedTypeName)
    {
        source.AppendLine();
        source.AppendLine("    public global::System.Threading.Tasks.ValueTask<TResponse> QueryAsync<TResponse>(");
        source.AppendLine("        global::Dispatcher.IQuery<TResponse> query,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(query);");
        source.AppendLine("        if (!QueryHandlers.TryGetValue(query.GetType(), out var entry))");
        source.AppendLine("        {");
        source.AppendLine("            throw new global::Dispatcher.HandlerNotFoundException(query.GetType());");
        source.AppendLine("        }");
        source.AppendLine("        if (entry.ResponseType != typeof(TResponse))");
        source.AppendLine("        {");
        source.AppendLine("            throw new global::System.InvalidOperationException($\"The generated handler shape does not match message type '{query.GetType().FullName}'.\");");
        source.AppendLine("        }");
        source.Append("        return global::System.Runtime.CompilerServices.Unsafe.As<global::System.Func<")
            .Append(generatedTypeName).AppendLine(", global::Dispatcher.IQuery<TResponse>, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask<TResponse>>>(entry.Handler)(this, query, cancellationToken);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public global::System.Threading.Tasks.ValueTask<TResponse> ExecuteAsync<TResponse>(");
        source.AppendLine("        global::Dispatcher.ICommand<TResponse> command,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(command);");
        source.AppendLine("        if (!ResponseCommandHandlers.TryGetValue(command.GetType(), out var entry))");
        source.AppendLine("        {");
        source.AppendLine("            throw new global::Dispatcher.HandlerNotFoundException(command.GetType());");
        source.AppendLine("        }");
        source.AppendLine("        if (entry.ResponseType != typeof(TResponse))");
        source.AppendLine("        {");
        source.AppendLine("            throw new global::System.InvalidOperationException($\"The generated handler shape does not match message type '{command.GetType().FullName}'.\");");
        source.AppendLine("        }");
        source.Append("        return global::System.Runtime.CompilerServices.Unsafe.As<global::System.Func<")
            .Append(generatedTypeName).AppendLine(", global::Dispatcher.ICommand<TResponse>, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask<TResponse>>>(entry.Handler)(this, command, cancellationToken);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public global::System.Threading.Tasks.ValueTask ExecuteAsync(");
        source.AppendLine("        global::Dispatcher.ICommand command,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(command);");
        source.AppendLine("        return CommandHandlers.TryGetValue(command.GetType(), out var handler)");
        source.AppendLine("            ? handler(this, command, cancellationToken)");
        source.AppendLine("            : global::System.Threading.Tasks.ValueTask.FromException(");
        source.AppendLine("                new global::Dispatcher.HandlerNotFoundException(command.GetType()));");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public global::System.Threading.Tasks.ValueTask PublishAsync<TNotification>(");
        source.AppendLine("        TNotification notification,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        source.AppendLine("        where TNotification : global::Dispatcher.INotification");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(notification);");
        source.AppendLine("        return NotificationHandlers.TryGetValue(notification.GetType(), out var handler)");
        source.AppendLine("            ? handler(this, notification, cancellationToken)");
        source.AppendLine("            : global::System.Threading.Tasks.ValueTask.CompletedTask;");
        source.AppendLine("    }");
    }

    private static void AppendCoreMethods(StringBuilder source)
    {
        source.AppendLine();
        source.AppendLine("    private global::System.Threading.Tasks.ValueTask<TResponse> QueryCore<TQuery, TResponse>(");
        source.AppendLine("        TQuery query, global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TQuery : global::Dispatcher.IQuery<TResponse> =>");
        source.AppendLine("        RequestCore<TQuery, TResponse>(query, GetRequiredService<global::Dispatcher.IQueryHandler<TQuery, TResponse>>(), cancellationToken);");
        source.AppendLine();
        source.AppendLine("    private global::System.Threading.Tasks.ValueTask<TResponse> ResponseCommandCore<TCommand, TResponse>(");
        source.AppendLine("        TCommand command, global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TCommand : global::Dispatcher.ICommand<TResponse> =>");
        source.AppendLine("        RequestCore<TCommand, TResponse>(command, GetRequiredService<global::Dispatcher.ICommandHandler<TCommand, TResponse>>(), cancellationToken);");
        source.AppendLine();
        source.AppendLine("    private global::System.Threading.Tasks.ValueTask<TResponse> RequestCore<TRequest, TResponse>(");
        source.AppendLine("        TRequest request,");
        source.AppendLine("        global::Dispatcher.IQueryHandler<TRequest, TResponse> handler,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TRequest : global::Dispatcher.IQuery<TResponse>");
        source.AppendLine("    {");
        source.AppendLine("        var behaviors = GetServices<global::Dispatcher.IPipelineBehavior<TRequest, TResponse>>();");
        source.AppendLine("        if (behaviors.Count == 0)");
        source.AppendLine("        {");
        source.AppendLine("            return handler.HandleAsync(request, cancellationToken);");
        source.AppendLine("        }");
        source.AppendLine("        return RunQueryPipeline(request, handler, behaviors, cancellationToken);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private global::System.Threading.Tasks.ValueTask<TResponse> RequestCore<TRequest, TResponse>(");
        source.AppendLine("        TRequest request,");
        source.AppendLine("        global::Dispatcher.ICommandHandler<TRequest, TResponse> handler,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TRequest : global::Dispatcher.ICommand<TResponse>");
        source.AppendLine("    {");
        source.AppendLine("        var behaviors = GetServices<global::Dispatcher.IPipelineBehavior<TRequest, TResponse>>();");
        source.AppendLine("        if (behaviors.Count == 0)");
        source.AppendLine("        {");
        source.AppendLine("            return handler.HandleAsync(request, cancellationToken);");
        source.AppendLine("        }");
        source.AppendLine("        return RunResponseCommandPipeline(request, handler, behaviors, cancellationToken);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static global::System.Threading.Tasks.ValueTask<TResponse> RunQueryPipeline<TRequest, TResponse>(");
        source.AppendLine("        TRequest request,");
        source.AppendLine("        global::Dispatcher.IQueryHandler<TRequest, TResponse> handler,");
        source.AppendLine("        global::System.Collections.Generic.IReadOnlyList<global::Dispatcher.IPipelineBehavior<TRequest, TResponse>> behaviors,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TRequest : global::Dispatcher.IQuery<TResponse>");
        source.AppendLine("    {");
        AppendPipelineBody(source, "request", "handler.HandleAsync(request, token)");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static global::System.Threading.Tasks.ValueTask<TResponse> RunResponseCommandPipeline<TRequest, TResponse>(");
        source.AppendLine("        TRequest request,");
        source.AppendLine("        global::Dispatcher.ICommandHandler<TRequest, TResponse> handler,");
        source.AppendLine("        global::System.Collections.Generic.IReadOnlyList<global::Dispatcher.IPipelineBehavior<TRequest, TResponse>> behaviors,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TRequest : global::Dispatcher.ICommand<TResponse>");
        source.AppendLine("    {");
        AppendPipelineBody(source, "request", "handler.HandleAsync(request, token)");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private global::System.Threading.Tasks.ValueTask CommandCore<TCommand>(");
        source.AppendLine("        TCommand command, global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TCommand : global::Dispatcher.ICommand");
        source.AppendLine("    {");
        source.AppendLine("        var handler = GetRequiredService<global::Dispatcher.ICommandHandler<TCommand>>();");
        source.AppendLine("        var behaviors = GetServices<global::Dispatcher.IPipelineBehavior<TCommand, global::Dispatcher.Unit>>();");
        source.AppendLine("        if (behaviors.Count == 0)");
        source.AppendLine("        {");
        source.AppendLine("            return handler.HandleAsync(command, cancellationToken);");
        source.AppendLine("        }");
        source.AppendLine("        return RunCommandPipeline(command, handler, behaviors, cancellationToken);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static async global::System.Threading.Tasks.ValueTask RunCommandPipeline<TCommand>(");
        source.AppendLine("        TCommand command,");
        source.AppendLine("        global::Dispatcher.ICommandHandler<TCommand> handler,");
        source.AppendLine("        global::System.Collections.Generic.IReadOnlyList<global::Dispatcher.IPipelineBehavior<TCommand, global::Dispatcher.Unit>> behaviors,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TCommand : global::Dispatcher.ICommand");
        source.AppendLine("    {");
        source.AppendLine("        global::Dispatcher.RequestHandlerDelegate<global::Dispatcher.Unit> pipeline = async token =>");
        source.AppendLine("        {");
        source.AppendLine("            await handler.HandleAsync(command, token).ConfigureAwait(false);");
        source.AppendLine("            return global::Dispatcher.Unit.Value;");
        source.AppendLine("        };");
        source.AppendLine("        for (var index = behaviors.Count - 1; index >= 1; index--)");
        source.AppendLine("        {");
        source.AppendLine("            var behavior = behaviors[index];");
        source.AppendLine("            var next = pipeline;");
        source.AppendLine("            pipeline = token => behavior.HandleAsync(command, next, token);");
        source.AppendLine("        }");
        source.AppendLine("        await behaviors[0].HandleAsync(command, pipeline, cancellationToken).ConfigureAwait(false);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private async global::System.Threading.Tasks.ValueTask NotificationCore<TNotification>(");
        source.AppendLine("        TNotification notification, global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TNotification : global::Dispatcher.INotification");
        source.AppendLine("    {");
        source.AppendLine("        var handlers = GetServices<global::Dispatcher.INotificationHandler<TNotification>>();");
        source.AppendLine("        for (var index = 0; index < handlers.Count; index++)");
        source.AppendLine("        {");
        source.AppendLine("            await handlers[index].HandleAsync(notification, cancellationToken).ConfigureAwait(false);");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private T GetRequiredService<T>() where T : notnull =>");
        source.AppendLine("        (T?)serviceProvider.GetService(typeof(T)) ??");
        source.AppendLine("        throw new global::System.InvalidOperationException($\"Service '{typeof(T).FullName}' is not registered.\");");
        source.AppendLine();
        source.AppendLine("    private global::System.Collections.Generic.IReadOnlyList<T> GetServices<T>()");
        source.AppendLine("    {");
        source.AppendLine("        var services = (global::System.Collections.Generic.IEnumerable<T>?)serviceProvider.GetService(");
        source.AppendLine("            typeof(global::System.Collections.Generic.IEnumerable<T>));");
        source.AppendLine("        return services switch");
        source.AppendLine("        {");
        source.AppendLine("            null => [],");
        source.AppendLine("            global::System.Collections.Generic.IReadOnlyList<T> list => list,");
        source.AppendLine("            _ => global::System.Linq.Enumerable.ToArray(services)");
        source.AppendLine("        };");
        source.AppendLine("    }");
    }

    private static void AppendRouteAvailabilityMethods(StringBuilder source)
    {
        source.AppendLine();
        source.AppendLine("    internal static bool HasQueryHandler(global::System.Type messageType, global::System.Type responseType) =>");
        source.AppendLine("        QueryHandlers.TryGetValue(messageType, out var entry) && entry.ResponseType == responseType;");
        source.AppendLine();
        source.AppendLine("    internal static bool HasResponseCommandHandler(global::System.Type messageType, global::System.Type responseType) =>");
        source.AppendLine("        ResponseCommandHandlers.TryGetValue(messageType, out var entry) && entry.ResponseType == responseType;");
        source.AppendLine();
        source.AppendLine("    internal static bool HasCommandHandler(global::System.Type messageType) =>");
        source.AppendLine("        CommandHandlers.ContainsKey(messageType);");
        source.AppendLine();
        source.AppendLine("    internal static bool HasNotificationHandlers(global::System.Type messageType) =>");
        source.AppendLine("        NotificationHandlers.ContainsKey(messageType);");
    }

    private static void AppendPipelineBody(StringBuilder source, string requestName, string handlerInvocation)
    {
        source.Append("        global::Dispatcher.RequestHandlerDelegate<TResponse> pipeline = token => ")
            .Append(handlerInvocation).AppendLine(";");
        source.AppendLine("        for (var index = behaviors.Count - 1; index >= 1; index--)");
        source.AppendLine("        {");
        source.AppendLine("            var behavior = behaviors[index];");
        source.AppendLine("            var next = pipeline;");
        source.Append("            pipeline = token => behavior.HandleAsync(").Append(requestName)
            .AppendLine(", next, token);");
        source.AppendLine("        }");
        source.Append("        return behaviors[0].HandleAsync(").Append(requestName)
            .AppendLine(", pipeline, cancellationToken);");
    }

    private static void AppendDispatcherContractRegistration(
        StringBuilder source,
        string contractType,
        string generatedTypeName,
        int indentation = 8)
    {
        var indent = new string(' ', indentation);
        source.Append(indent).Append("services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(")
            .Append(contractType).AppendLine("), static provider =>");
        source.Append(indent).Append("    provider.GetService(typeof(").Append(generatedTypeName).AppendLine(")) ??");
        source.Append(indent).Append("    throw new global::System.InvalidOperationException(\"Service '")
            .Append(generatedTypeName).AppendLine("' is not registered.\"), options.ServiceLifetime));");
    }
}