using System.Text;
using Dispatcher.SourceGeneration.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Dispatcher.SourceGeneration.Emission;

internal static class HandlerRegistrationEmitter
{
    internal static void Emit(SourceProductionContext context, GenerationResult result)
    {
        var className = IdentifierSanitizer.SanitizeIdentifier(result.AssemblyName) + "DispatcherGeneratedExtensions";
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("namespace Dispatcher.SourceGeneration;");
        source.AppendLine();
        source.Append("public static class ").Append(className).AppendLine();
        source.AppendLine("{");
        source.Append("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection ")
            .Append(result.MethodName)
            .AppendLine("(");
        source.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        source.Append("        => ").Append(result.MethodName)
            .AppendLine("(services, static _ => { });");
        source.AppendLine();
        source.Append("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection ")
            .Append(result.MethodName)
            .AppendLine("(");
        source.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        source.AppendLine("        global::System.Action<global::Dispatcher.DependencyInjection.DispatcherOptions> configure)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(services);");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(configure);");
        source.AppendLine("        var options = new global::Dispatcher.DependencyInjection.DispatcherOptions();");
        source.AppendLine("        configure(options);");

        foreach (var handler in result.LocalHandlers)
        {
            source.Append("        global::Dispatcher.DependencyInjection.Extensions.TypedDispatcherServiceCollectionExtensions.")
                .Append(handler.MethodName)
                .Append('<')
                .Append(handler.TypeArguments)
                .AppendLine(">(services, handlerOptions => handlerOptions.ServiceLifetime = options.ServiceLifetime);");
        }

        source.AppendLine();
        source.AppendLine("        return services;");
        source.AppendLine("    }");
        source.AppendLine("}");

        context.AddSource(className + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }
}