using System.Text;
using Dispatcher.SourceGeneration.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Dispatcher.SourceGeneration.Emission;

internal static class HandlerRegistrationEmitter
{
    internal static void Emit(SourceProductionContext context, GenerationResult result)
    {
        var className = IdentifierSanitizer.SanitizeIdentifier(result.AssemblyName) + "DispatcherGeneratedExtensions";
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("namespace Microsoft.Extensions.DependencyInjection;");
        source.AppendLine();
        source.Append("public static class ").Append(className).AppendLine();
        source.AppendLine("{");
        source.Append("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection ")
            .Append(result.MethodName)
            .AppendLine("(");
        source.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(services);");

        foreach (var handler in result.LocalHandlers)
        {
            source.Append("        global::Dispatcher.Extensions.Microsoft.DependencyInjection.TypedDispatcherServiceCollectionExtensions.")
                .Append(handler.MethodName)
                .Append('<')
                .Append(handler.TypeArguments)
                .AppendLine(">(services);");
        }

        source.AppendLine();
        source.AppendLine("        return services;");
        source.AppendLine("    }");
        source.AppendLine("}");

        context.AddSource(className + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }
}