using System.Text;
using Dispatcher.SourceGeneration.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Dispatcher.SourceGeneration.Emission;

internal static class HandlerRegistrationEmitter
{
    internal static void Emit(SourceProductionContext context, GenerationResult result)
    {
        var className = IdentifierSanitizer.SanitizeIdentifier(result.AssemblyName) + "DispatcherGeneratedExtensions";
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("namespace Dispatcher.SourceGeneration;");
        source.AppendLine();
        source.AppendLine("/// <summary>");
        source.AppendLine("/// Provides registration methods for source-generated handlers in this assembly.");
        source.AppendLine("/// </summary>");
        source.Append("public static class ").Append(className).AppendLine();
        source.AppendLine("{");
        source.AppendLine("    /// <summary>");
        source.AppendLine("    /// Registers the source-generated handlers in this assembly.");
        source.AppendLine("    /// </summary>");
        source.AppendLine("    /// <param name=\"services\">The service collection to add the handlers to.</param>");
        source.AppendLine("    /// <returns>The same service collection so that additional calls can be chained.</returns>");
        source.AppendLine("    /// <exception cref=\"global::System.ArgumentNullException\">");
        source.AppendLine("    /// <paramref name=\"services\"/> is <see langword=\"null\"/>.");
        source.AppendLine("    /// </exception>");
        source.Append("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection ")
            .Append(result.MethodName)
            .AppendLine("(");
        source.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        source.Append("        => ").Append(result.MethodName)
            .AppendLine("(services, static _ => { });");
        source.AppendLine();
        source.AppendLine("    /// <summary>");
        source.AppendLine("    /// Registers the source-generated handlers in this assembly using the specified options.");
        source.AppendLine("    /// </summary>");
        source.AppendLine("    /// <param name=\"services\">The service collection to add the handlers to.</param>");
        source.AppendLine("    /// <param name=\"configure\">The delegate that configures handler registration.</param>");
        source.AppendLine("    /// <returns>The same service collection so that additional calls can be chained.</returns>");
        source.AppendLine("    /// <exception cref=\"global::System.ArgumentNullException\">");
        source.AppendLine("    /// <paramref name=\"services\"/> or <paramref name=\"configure\"/> is <see langword=\"null\"/>.");
        source.AppendLine("    /// </exception>");
        source.Append("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection ")
            .Append(result.MethodName)
            .AppendLine("(");
        source.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        source.AppendLine("        global::System.Action<global::Dispatcher.DispatcherOptions> configure)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(services);");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(configure);");
        source.AppendLine("        var options = new global::Dispatcher.DispatcherOptions();");
        source.AppendLine("        configure(options);");

        foreach (var handler in result.LocalHandlers)
        {
            source.Append("        global::Dispatcher.ServiceCollectionExtensions.")
                .Append(handler.MethodName)
                .Append('<')
                .Append(handler.TypeArguments)
                .AppendLine(">(services, handlerOptions => handlerOptions.ServiceLifetime = options.ServiceLifetime);");
        }

        source.AppendLine();
        source.AppendLine("        return services;");
        source.AppendLine("    }");
        source.AppendLine("}");

        context.AddSource(className + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }
}