using System.Collections.Immutable;
using System.Text;
using Dispatcher.SourceGeneration.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Dispatcher.SourceGeneration.Emission;

internal static class PipelineBehaviorEmitter
{
    internal static void Emit(
        SourceProductionContext context,
        GenerationResult result)
    {
        var requests = result.DispatchHandlers
            .Where(handler => handler.Kind != HandlerModelKind.Notification)
            .Select(handler => new
            {
                Request = handler.MessageType,
                Response = handler.Kind == HandlerModelKind.Command
                    ? ((INamedTypeSymbol)handler.MessageType).AllInterfaces
                        .First(@interface => @interface.OriginalDefinition.ToDisplayString() ==
                            "Dispatcher.ICommand<TResponse>").TypeArguments[0]
                    : handler.ResponseType
            })
            .Where(item => item.Response is not null)
            .GroupBy(item => item.Request.ToDisplayString(SymbolDisplayFormats.FullyQualified) + "|" +
                item.Response!.ToDisplayString(SymbolDisplayFormats.FullyQualified), StringComparer.Ordinal)
            .Select(group => group.First())
            .ToArray();
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("namespace Dispatcher.SourceGeneration;");
        source.AppendLine();
        source.AppendLine("public static class GeneratedPipelineBehaviorServiceCollectionExtensions");
        source.AppendLine("{");
        source.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddPipelineBehavior(");
        source.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        source.AppendLine("        global::System.Type behaviorType)");
        source.AppendLine("        => AddPipelineBehavior(services, behaviorType, static _ => { });");
        source.AppendLine();
        source.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddPipelineBehavior(");
        source.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        source.AppendLine("        global::System.Type behaviorType,");
        source.AppendLine("        global::System.Action<global::Dispatcher.DispatcherOptions> configure)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(services);");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(behaviorType);");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(configure);");
        source.AppendLine("        var options = new global::Dispatcher.DispatcherOptions();");
        source.AppendLine("        configure(options);");

        foreach (var behavior in result.OpenBehaviors)
        {
            source.Append("        if (behaviorType == typeof(")
                .Append(behavior.ConstructUnboundGenericType().ToDisplayString(SymbolDisplayFormats.FullyQualified))
                .AppendLine("))");
            source.AppendLine("        {");
            foreach (var request in requests)
            {
                var response = request.Response!;
                if (!CanCloseBehavior(behavior, request.Request, response))
                {
                    continue;
                }

                source.Append("            global::Dispatcher.ServiceCollectionExtensions.AddPipelineBehavior<")
                    .Append(request.Request.ToDisplayString(SymbolDisplayFormats.FullyQualified)).Append(", ")
                    .Append(response.ToDisplayString(SymbolDisplayFormats.FullyQualified)).Append(", ")
                    .Append(behavior.Construct(request.Request, response).ToDisplayString(SymbolDisplayFormats.FullyQualified))
                    .AppendLine(">(services, behaviorOptions => behaviorOptions.ServiceLifetime = options.ServiceLifetime);");
            }
            source.AppendLine("            return services;");
            source.AppendLine("        }");
        }

        source.AppendLine();
        source.AppendLine("        throw new global::System.ArgumentException(");
        source.AppendLine("            $\"Pipeline behavior '{behaviorType.FullName}' was not discovered by the Dispatcher generator.\",");
        source.AppendLine("            nameof(behaviorType));");
        source.AppendLine("    }");
        source.AppendLine("}");
        context.AddSource(
            "GeneratedPipelineBehaviorServiceCollectionExtensions.g.cs",
            SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static bool CanCloseBehavior(
        INamedTypeSymbol behavior,
        ITypeSymbol request,
        ITypeSymbol response)
    {
        ITypeSymbol[] arguments = [request, response];
        for (var index = 0; index < behavior.TypeParameters.Length; index++)
        {
            var parameter = behavior.TypeParameters[index];
            var argument = arguments[index];
            if (parameter.HasUnmanagedTypeConstraint && !argument.IsUnmanagedType ||
                parameter.HasReferenceTypeConstraint && !argument.IsReferenceType ||
                parameter.HasValueTypeConstraint && !argument.IsValueType ||
                parameter.HasConstructorConstraint &&
                argument is INamedTypeSymbol namedArgument &&
                !namedArgument.InstanceConstructors.Any(constructor =>
                    constructor.Parameters.IsEmpty && constructor.DeclaredAccessibility == Accessibility.Public))
            {
                return false;
            }

            foreach (var constraint in parameter.ConstraintTypes)
            {
                var closedConstraint = SubstituteTypeParameters(constraint, behavior.TypeParameters, arguments);
                if (!SatisfiesTypeConstraint(argument, closedConstraint))
                {
                    return false;
                }
            }
        }

        return true;
    }

    private static ITypeSymbol SubstituteTypeParameters(
        ITypeSymbol type,
        ImmutableArray<ITypeParameterSymbol> parameters,
        IReadOnlyList<ITypeSymbol> arguments)
    {
        if (type is ITypeParameterSymbol parameter)
        {
            var index = parameters.IndexOf(parameter, SymbolEqualityComparer.Default);
            return index >= 0 ? arguments[index] : type;
        }

        if (type is not INamedTypeSymbol namedType || !namedType.IsGenericType)
        {
            return type;
        }

        return namedType.OriginalDefinition.Construct(namedType.TypeArguments
            .Select(argument => SubstituteTypeParameters(argument, parameters, arguments))
            .ToArray());
    }

    private static bool SatisfiesTypeConstraint(ITypeSymbol argument, ITypeSymbol constraint)
    {
        if (SymbolEqualityComparer.Default.Equals(argument, constraint))
        {
            return true;
        }

        if (argument is not INamedTypeSymbol namedArgument)
        {
            return false;
        }

        if (namedArgument.AllInterfaces.Any(@interface =>
                SymbolEqualityComparer.Default.Equals(@interface, constraint)))
        {
            return true;
        }

        for (var baseType = namedArgument.BaseType; baseType is not null; baseType = baseType.BaseType)
        {
            if (SymbolEqualityComparer.Default.Equals(baseType, constraint))
            {
                return true;
            }
        }

        return false;
    }
}