<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PublishAot>true</PublishAot>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Dispatcher.NativeAotSample.Module/Dispatcher.NativeAotSample.Module.csproj" />
    <ProjectReference Include="../../../../src/Dispatcher.Extensions.Microsoft.DependencyInjection/Dispatcher.Extensions.Microsoft.DependencyInjection.csproj" />
    <PackageReference Include="FluentValidation" />
  </ItemGroup>
</Project>
