using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Dispatcher.SourceGeneration;

[Generator(LanguageNames.CSharp)]
public sealed class DispatcherGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "Dispatcher.GenerateDispatcherHandlersAttribute";
    private const string QueryHandlerMetadataName = "Dispatcher.IQueryHandler`2";
    private const string CommandHandlerMetadataName = "Dispatcher.ICommandHandler`2";
    private const string CommandWithoutResponseHandlerMetadataName = "Dispatcher.ICommandHandler`1";
    private const string NotificationHandlerMetadataName = "Dispatcher.INotificationHandler`1";
    private const string QueryMetadataName = "Dispatcher.IQuery`1";
    private const string CommandMetadataName = "Dispatcher.ICommand`1";
    private const string CommandWithoutResponseMetadataName = "Dispatcher.ICommand";

    private static readonly SymbolDisplayFormat TypeDisplayFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions |
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    private static readonly DiagnosticDescriptor InvalidMethodName = new(
        "DSPG001",
        "Invalid generated registration method name",
        "'{0}' is not a valid generated registration method name",
        "Dispatcher.SourceGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor DuplicateRequestHandler = new(
        "DSPG002",
        "Multiple request handlers",
        "Request '{0}' has multiple handlers: {1}",
        "Dispatcher.SourceGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor OpenGenericHandler = new(
        "DSPG003",
        "Open generic handlers are unsupported",
        "Handler '{0}' is open generic and cannot be registered by the generator",
        "Dispatcher.SourceGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor HandlerCannotBeActivated = new(
        "DSPG004",
        "Handler cannot be activated",
        "Handler '{0}' must be accessible and expose at least one public constructor",
        "Dispatcher.SourceGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor MissingRequestHandler = new(
        "DSPG005",
        "Request has no handler",
        "Request '{0}' has no handler in this generated module",
        "Dispatcher.SourceGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static postInitializationContext =>
            postInitializationContext.AddSource(
                "GenerateDispatcherHandlersAttribute.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8)));

        var model = context.CompilationProvider.Select(static (compilation, cancellationToken) =>
            Analyze(compilation, cancellationToken));

        context.RegisterSourceOutput(model, static (productionContext, result) =>
            Emit(productionContext, result));
    }

    private const string AttributeSource = """
        // <auto-generated />
        #nullable enable

        namespace Dispatcher;

        [global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]
        internal sealed class GenerateDispatcherHandlersAttribute : global::System.Attribute
        {
            public GenerateDispatcherHandlersAttribute(string methodName)
            {
                MethodName = methodName;
            }

            public string MethodName { get; }
        }
        """;

    private static GenerationResult Analyze(Compilation compilation, CancellationToken cancellationToken)
    {
        var attributeType = compilation.GetTypeByMetadataName(AttributeMetadataName);
        if (attributeType is null)
        {
            return GenerationResult.Empty;
        }

        var attribute = compilation.Assembly.GetAttributes()
            .FirstOrDefault(candidate => SymbolEqualityComparer.Default.Equals(candidate.AttributeClass, attributeType));
        if (attribute is null)
        {
            return GenerationResult.Empty;
        }

        var methodName = attribute.ConstructorArguments.Length == 1
            ? attribute.ConstructorArguments[0].Value as string
            : null;
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();
        var attributeLocation = attribute.ApplicationSyntaxReference?.GetSyntax(cancellationToken).GetLocation();

        if (string.IsNullOrWhiteSpace(methodName) ||
            !SyntaxFacts.IsValidIdentifier(methodName) ||
            SyntaxFacts.GetKeywordKind(methodName) != SyntaxKind.None)
        {
            diagnostics.Add(Diagnostic.Create(
                InvalidMethodName,
                attributeLocation,
                methodName ?? string.Empty));
            return new GenerationResult(null, ImmutableArray<HandlerModel>.Empty, diagnostics.ToImmutable());
        }

        var queryHandler = compilation.GetTypeByMetadataName(QueryHandlerMetadataName);
        var commandHandler = compilation.GetTypeByMetadataName(CommandHandlerMetadataName);
        var commandWithoutResponseHandler = compilation.GetTypeByMetadataName(
            CommandWithoutResponseHandlerMetadataName);
        var notificationHandler = compilation.GetTypeByMetadataName(NotificationHandlerMetadataName);
        if (queryHandler is null || commandHandler is null || commandWithoutResponseHandler is null ||
            notificationHandler is null)
        {
            return new GenerationResult(methodName, ImmutableArray<HandlerModel>.Empty, diagnostics.ToImmutable());
        }

        var allTypes = GetAllTypes(compilation.Assembly.GlobalNamespace).ToImmutableArray();
        var handlers = ImmutableArray.CreateBuilder<HandlerModel>();

        foreach (var type in allTypes)
        {
            cancellationToken.ThrowIfCancellationRequested();

            var implementedHandlers = type.AllInterfaces
                .Where(@interface => IsHandlerInterface(
                    @interface.OriginalDefinition,
                    queryHandler,
                    commandHandler,
                    commandWithoutResponseHandler,
                    notificationHandler))
                .ToImmutableArray();
            if (implementedHandlers.IsDefaultOrEmpty)
            {
                continue;
            }

            if (type.Arity != 0 || implementedHandlers.Any(ContainsTypeParameter))
            {
                diagnostics.Add(Diagnostic.Create(
                    OpenGenericHandler,
                    type.Locations.FirstOrDefault(),
                    type.ToDisplayString(TypeDisplayFormat)));
                continue;
            }

            if (type.TypeKind != TypeKind.Class || type.IsAbstract ||
                !compilation.IsSymbolAccessibleWithin(type, compilation.Assembly) ||
                !type.InstanceConstructors.Any(constructor =>
                    !constructor.IsStatic && constructor.DeclaredAccessibility == Accessibility.Public))
            {
                diagnostics.Add(Diagnostic.Create(
                    HandlerCannotBeActivated,
                    type.Locations.FirstOrDefault(),
                    type.ToDisplayString(TypeDisplayFormat)));
                continue;
            }

            foreach (var handlerInterface in implementedHandlers)
            {
                handlers.Add(CreateHandlerModel(
                    type,
                    handlerInterface,
                    queryHandler,
                    commandHandler,
                    commandWithoutResponseHandler));
            }
        }

        AddDuplicateDiagnostics(handlers, diagnostics);
        AddMissingHandlerDiagnostics(compilation, allTypes, handlers, diagnostics);

        return new GenerationResult(
            methodName,
            handlers.OrderBy(handler => handler.SortKey, StringComparer.Ordinal).ToImmutableArray(),
            diagnostics.ToImmutable(),
            compilation.AssemblyName ?? "DispatcherModule");
    }

    private static HandlerModel CreateHandlerModel(
        INamedTypeSymbol implementation,
        INamedTypeSymbol handlerInterface,
        INamedTypeSymbol queryHandler,
        INamedTypeSymbol commandHandler,
        INamedTypeSymbol commandWithoutResponseHandler)
    {
        var definition = handlerInterface.OriginalDefinition;
        var kind = SymbolEqualityComparer.Default.Equals(definition, queryHandler)
            ? HandlerModelKind.Query
            : SymbolEqualityComparer.Default.Equals(definition, commandHandler)
                ? HandlerModelKind.CommandWithResponse
                : SymbolEqualityComparer.Default.Equals(definition, commandWithoutResponseHandler)
                    ? HandlerModelKind.Command
                    : HandlerModelKind.Notification;

        return new HandlerModel(
            kind,
            handlerInterface.TypeArguments[0],
            handlerInterface.TypeArguments.Length == 2 ? handlerInterface.TypeArguments[1] : null,
            implementation);
    }

    private static void AddDuplicateDiagnostics(
        ImmutableArray<HandlerModel>.Builder handlers,
        ImmutableArray<Diagnostic>.Builder diagnostics)
    {
        foreach (var group in handlers
                     .Where(handler => handler.Kind != HandlerModelKind.Notification)
                     .GroupBy(handler => handler.MessageType, SymbolEqualityComparer.Default)
                     .Where(group => group.Count() > 1))
        {
            var implementations = string.Join(
                ", ",
                group.Select(handler => handler.ImplementationType.ToDisplayString(TypeDisplayFormat))
                    .OrderBy(name => name, StringComparer.Ordinal));
            diagnostics.Add(Diagnostic.Create(
                DuplicateRequestHandler,
                group.Key!.Locations.FirstOrDefault(),
                group.Key.ToDisplayString(TypeDisplayFormat),
                implementations));
        }
    }

    private static void AddMissingHandlerDiagnostics(
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol> allTypes,
        ImmutableArray<HandlerModel>.Builder handlers,
        ImmutableArray<Diagnostic>.Builder diagnostics)
    {
        var query = compilation.GetTypeByMetadataName(QueryMetadataName);
        var command = compilation.GetTypeByMetadataName(CommandMetadataName);
        var commandWithoutResponse = compilation.GetTypeByMetadataName(CommandWithoutResponseMetadataName);
        if (query is null || command is null || commandWithoutResponse is null)
        {
            return;
        }

        foreach (var type in allTypes.Where(type =>
                     type.Locations.Any(location => location.IsInSource) &&
                     type.Arity == 0 &&
                     !type.IsAbstract &&
                     IsRequest(type, query, command, commandWithoutResponse)))
        {
            if (handlers.Any(handler => SymbolEqualityComparer.Default.Equals(handler.MessageType, type)))
            {
                continue;
            }

            diagnostics.Add(Diagnostic.Create(
                MissingRequestHandler,
                type.Locations.FirstOrDefault(),
                type.ToDisplayString(TypeDisplayFormat)));
        }
    }

    private static bool IsRequest(
        INamedTypeSymbol type,
        INamedTypeSymbol query,
        INamedTypeSymbol command,
        INamedTypeSymbol commandWithoutResponse) =>
        type.AllInterfaces.Any(@interface =>
            SymbolEqualityComparer.Default.Equals(@interface.OriginalDefinition, query) ||
            SymbolEqualityComparer.Default.Equals(@interface.OriginalDefinition, command) ||
            SymbolEqualityComparer.Default.Equals(@interface, commandWithoutResponse));

    private static bool IsHandlerInterface(
        INamedTypeSymbol definition,
        INamedTypeSymbol queryHandler,
        INamedTypeSymbol commandHandler,
        INamedTypeSymbol commandWithoutResponseHandler,
        INamedTypeSymbol notificationHandler) =>
        SymbolEqualityComparer.Default.Equals(definition, queryHandler) ||
        SymbolEqualityComparer.Default.Equals(definition, commandHandler) ||
        SymbolEqualityComparer.Default.Equals(definition, commandWithoutResponseHandler) ||
        SymbolEqualityComparer.Default.Equals(definition, notificationHandler);

    private static bool ContainsTypeParameter(INamedTypeSymbol type) =>
        type.TypeArguments.Any(argument => argument.TypeKind == TypeKind.TypeParameter);

    private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol @namespace)
    {
        foreach (var type in @namespace.GetTypeMembers())
        {
            foreach (var nestedType in GetTypeAndNestedTypes(type))
            {
                yield return nestedType;
            }
        }

        foreach (var childNamespace in @namespace.GetNamespaceMembers())
        {
            foreach (var type in GetAllTypes(childNamespace))
            {
                yield return type;
            }
        }
    }

    private static IEnumerable<INamedTypeSymbol> GetTypeAndNestedTypes(INamedTypeSymbol type)
    {
        yield return type;

        foreach (var nestedType in type.GetTypeMembers())
        {
            foreach (var descendant in GetTypeAndNestedTypes(nestedType))
            {
                yield return descendant;
            }
        }
    }

    private static void Emit(SourceProductionContext context, GenerationResult result)
    {
        foreach (var diagnostic in result.Diagnostics)
        {
            context.ReportDiagnostic(diagnostic);
        }

        if (result.MethodName is null || result.Diagnostics.Any(diagnostic =>
                diagnostic.Severity == DiagnosticSeverity.Error))
        {
            return;
        }

        var className = SanitizeIdentifier(result.AssemblyName) + "DispatcherGeneratedExtensions";
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace Dispatcher.Extensions.Microsoft.DependencyInjection;");
        source.AppendLine();
        source.Append("public static class ").Append(className).AppendLine();
        source.AppendLine("{");
        source.Append("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection ")
            .Append(result.MethodName)
            .AppendLine("(");
        source.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(services);");

        foreach (var handler in result.Handlers)
        {
            source.Append("        global::Dispatcher.Extensions.Microsoft.DependencyInjection.TypedDispatcherServiceCollectionExtensions.")
                .Append(handler.MethodName)
                .Append('<')
                .Append(handler.TypeArguments)
                .AppendLine(">(services);");
        }

        source.AppendLine();
        source.AppendLine("        return services;");
        source.AppendLine("    }");
        source.AppendLine("}");

        context.AddSource(className + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static string SanitizeIdentifier(string value)
    {
        var builder = new StringBuilder(value.Length + 1);
        if (value.Length == 0 || !SyntaxFacts.IsIdentifierStartCharacter(value[0]))
        {
            builder.Append('_');
        }

        foreach (var character in value)
        {
            builder.Append(SyntaxFacts.IsIdentifierPartCharacter(character) ? character : '_');
        }

        return builder.ToString();
    }

    private enum HandlerModelKind
    {
        Query,
        CommandWithResponse,
        Command,
        Notification
    }

    private sealed class HandlerModel
    {
        public HandlerModel(
            HandlerModelKind kind,
            ITypeSymbol messageType,
            ITypeSymbol? responseType,
            INamedTypeSymbol implementationType)
        {
            Kind = kind;
            MessageType = messageType;
            ResponseType = responseType;
            ImplementationType = implementationType;
        }

        public HandlerModelKind Kind { get; }
        public ITypeSymbol MessageType { get; }
        public ITypeSymbol? ResponseType { get; }
        public INamedTypeSymbol ImplementationType { get; }
        public string SortKey => MessageType.ToDisplayString(TypeDisplayFormat) + "|" +
            ImplementationType.ToDisplayString(TypeDisplayFormat);
        public string MethodName => Kind switch
        {
            HandlerModelKind.Query => "AddQueryHandler",
            HandlerModelKind.CommandWithResponse => "AddCommandHandler",
            HandlerModelKind.Command => "AddCommandHandler",
            _ => "AddNotificationHandler"
        };
        public string TypeArguments => ResponseType is null
            ? MessageType.ToDisplayString(TypeDisplayFormat) + ", " +
              ImplementationType.ToDisplayString(TypeDisplayFormat)
            : MessageType.ToDisplayString(TypeDisplayFormat) + ", " +
              ResponseType.ToDisplayString(TypeDisplayFormat) + ", " +
              ImplementationType.ToDisplayString(TypeDisplayFormat);
    }

    private sealed class GenerationResult
    {
        public static readonly GenerationResult Empty = new(
            null,
            ImmutableArray<HandlerModel>.Empty,
            ImmutableArray<Diagnostic>.Empty);

        public GenerationResult(
            string? methodName,
            ImmutableArray<HandlerModel> handlers,
            ImmutableArray<Diagnostic> diagnostics,
            string assemblyName = "")
        {
            MethodName = methodName;
            Handlers = handlers;
            Diagnostics = diagnostics;
            AssemblyName = assemblyName;
        }

        public string? MethodName { get; }
        public ImmutableArray<HandlerModel> Handlers { get; }
        public ImmutableArray<Diagnostic> Diagnostics { get; }
        public string AssemblyName { get; }
    }
}