using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Dispatcher.SourceGeneration;

[Generator(LanguageNames.CSharp)]
public sealed class DispatcherGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "Dispatcher.GenerateDispatcherHandlersAttribute";
    private const string DispatcherAttributeMetadataName = "Dispatcher.GenerateDispatcherAttribute";
    private const string QueryHandlerMetadataName = "Dispatcher.IQueryHandler`2";
    private const string CommandHandlerMetadataName = "Dispatcher.ICommandHandler`2";
    private const string CommandWithoutResponseHandlerMetadataName = "Dispatcher.ICommandHandler`1";
    private const string NotificationHandlerMetadataName = "Dispatcher.INotificationHandler`1";
    private const string QueryMetadataName = "Dispatcher.IQuery`1";
    private const string CommandMetadataName = "Dispatcher.ICommand`1";
    private const string CommandWithoutResponseMetadataName = "Dispatcher.ICommand";

    private static readonly SymbolDisplayFormat TypeDisplayFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions |
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    private static readonly DiagnosticDescriptor InvalidMethodName = new(
        "DSPG001",
        "Invalid generated registration method name",
        "'{0}' is not a valid generated registration method name",
        "Dispatcher.SourceGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor DuplicateRequestHandler = new(
        "DSPG002",
        "Multiple request handlers",
        "Request '{0}' has multiple handlers: {1}",
        "Dispatcher.SourceGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor OpenGenericHandler = new(
        "DSPG003",
        "Open generic handlers are unsupported",
        "Handler '{0}' is open generic and cannot be registered by the generator",
        "Dispatcher.SourceGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor HandlerCannotBeActivated = new(
        "DSPG004",
        "Handler cannot be activated",
        "Handler '{0}' must be accessible and expose at least one public constructor",
        "Dispatcher.SourceGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor MissingRequestHandler = new(
        "DSPG005",
        "Request has no handler",
        "Request '{0}' has no handler in this generated module",
        "Dispatcher.SourceGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor InvalidDispatcherMethodName = new(
        "DSPG006",
        "Invalid generated dispatcher registration method name",
        "'{0}' is not a valid generated dispatcher registration method name",
        "Dispatcher.SourceGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor InaccessibleReferencedMessage = new(
        "DSPG007",
        "Referenced message is inaccessible",
        "Message '{0}' handled by module '{1}' must be accessible to the generated host dispatcher",
        "Dispatcher.SourceGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static postInitializationContext =>
        {
            postInitializationContext.AddSource(
                "GenerateDispatcherHandlersAttribute.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8));
            postInitializationContext.AddSource(
                "GenerateDispatcherAttribute.g.cs",
                SourceText.From(DispatcherAttributeSource, Encoding.UTF8));
        });

        var model = context.CompilationProvider.Select(static (compilation, cancellationToken) =>
            Analyze(compilation, cancellationToken));

        context.RegisterSourceOutput(model, static (productionContext, result) =>
            Emit(productionContext, result));
    }

    private const string AttributeSource = """
        // <auto-generated />
        #nullable enable

        namespace Dispatcher;

        [global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]
        internal sealed class GenerateDispatcherHandlersAttribute : global::System.Attribute
        {
            public GenerateDispatcherHandlersAttribute(string methodName)
            {
                MethodName = methodName;
            }

            public string MethodName { get; }
        }
        """;

    private const string DispatcherAttributeSource = """
        // <auto-generated />
        #nullable enable

        namespace Dispatcher;

        [global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]
        internal sealed class GenerateDispatcherAttribute : global::System.Attribute
        {
            public GenerateDispatcherAttribute(string methodName)
            {
                MethodName = methodName;
            }

            public string MethodName { get; }
        }
        """;

    private static GenerationResult Analyze(Compilation compilation, CancellationToken cancellationToken)
    {
        var attributeType = compilation.GetTypeByMetadataName(AttributeMetadataName);
        var dispatcherAttributeType = compilation.GetTypeByMetadataName(DispatcherAttributeMetadataName);
        if (attributeType is null || dispatcherAttributeType is null)
        {
            return GenerationResult.Empty;
        }

        var attribute = compilation.Assembly.GetAttributes()
            .FirstOrDefault(candidate => SymbolEqualityComparer.Default.Equals(candidate.AttributeClass, attributeType));
        var dispatcherAttribute = compilation.Assembly.GetAttributes()
            .FirstOrDefault(candidate =>
                SymbolEqualityComparer.Default.Equals(candidate.AttributeClass, dispatcherAttributeType));
        if (attribute is null && dispatcherAttribute is null)
        {
            return GenerationResult.Empty;
        }

        var methodName = attribute?.ConstructorArguments.Length == 1
            ? attribute.ConstructorArguments[0].Value as string
            : null;
        var dispatcherMethodName = dispatcherAttribute?.ConstructorArguments.Length == 1
            ? dispatcherAttribute.ConstructorArguments[0].Value as string
            : null;
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();
        var attributeLocation = attribute?.ApplicationSyntaxReference?.GetSyntax(cancellationToken).GetLocation();

        if (attribute is not null && (string.IsNullOrWhiteSpace(methodName) ||
            !SyntaxFacts.IsValidIdentifier(methodName) ||
            SyntaxFacts.GetKeywordKind(methodName) != SyntaxKind.None))
        {
            diagnostics.Add(Diagnostic.Create(
                InvalidMethodName,
                attributeLocation,
                methodName ?? string.Empty));
            return new GenerationResult(
                null,
                dispatcherMethodName,
                ImmutableArray<HandlerModel>.Empty,
                ImmutableArray<HandlerModel>.Empty,
                diagnostics.ToImmutable());
        }

        if (dispatcherAttribute is not null && (string.IsNullOrWhiteSpace(dispatcherMethodName) ||
            !SyntaxFacts.IsValidIdentifier(dispatcherMethodName) ||
            SyntaxFacts.GetKeywordKind(dispatcherMethodName) != SyntaxKind.None))
        {
            diagnostics.Add(Diagnostic.Create(
                InvalidDispatcherMethodName,
                dispatcherAttribute.ApplicationSyntaxReference?.GetSyntax(cancellationToken).GetLocation(),
                dispatcherMethodName ?? string.Empty));
            return new GenerationResult(
                methodName,
                null,
                ImmutableArray<HandlerModel>.Empty,
                ImmutableArray<HandlerModel>.Empty,
                diagnostics.ToImmutable());
        }

        var queryHandler = compilation.GetTypeByMetadataName(QueryHandlerMetadataName);
        var commandHandler = compilation.GetTypeByMetadataName(CommandHandlerMetadataName);
        var commandWithoutResponseHandler = compilation.GetTypeByMetadataName(
            CommandWithoutResponseHandlerMetadataName);
        var notificationHandler = compilation.GetTypeByMetadataName(NotificationHandlerMetadataName);
        if (queryHandler is null || commandHandler is null || commandWithoutResponseHandler is null ||
            notificationHandler is null)
        {
            return new GenerationResult(
                methodName,
                dispatcherMethodName,
                ImmutableArray<HandlerModel>.Empty,
                ImmutableArray<HandlerModel>.Empty,
                diagnostics.ToImmutable());
        }

        var allTypes = GetAllTypes(compilation.Assembly.GlobalNamespace).ToImmutableArray();
        var handlers = ImmutableArray.CreateBuilder<HandlerModel>();

        foreach (var type in allTypes)
        {
            cancellationToken.ThrowIfCancellationRequested();

            var implementedHandlers = type.AllInterfaces
                .Where(@interface => IsHandlerInterface(
                    @interface.OriginalDefinition,
                    queryHandler,
                    commandHandler,
                    commandWithoutResponseHandler,
                    notificationHandler))
                .ToImmutableArray();
            if (implementedHandlers.IsDefaultOrEmpty)
            {
                continue;
            }

            if (type.Arity != 0 || implementedHandlers.Any(ContainsTypeParameter))
            {
                diagnostics.Add(Diagnostic.Create(
                    OpenGenericHandler,
                    type.Locations.FirstOrDefault(),
                    type.ToDisplayString(TypeDisplayFormat)));
                continue;
            }

            if (type.TypeKind != TypeKind.Class || type.IsAbstract ||
                !compilation.IsSymbolAccessibleWithin(type, compilation.Assembly) ||
                !type.InstanceConstructors.Any(constructor =>
                    !constructor.IsStatic && constructor.DeclaredAccessibility == Accessibility.Public))
            {
                diagnostics.Add(Diagnostic.Create(
                    HandlerCannotBeActivated,
                    type.Locations.FirstOrDefault(),
                    type.ToDisplayString(TypeDisplayFormat)));
                continue;
            }

            foreach (var handlerInterface in implementedHandlers)
            {
                handlers.Add(CreateHandlerModel(
                    type,
                    handlerInterface,
                    queryHandler,
                    commandHandler,
                    commandWithoutResponseHandler));
            }
        }

        AddMissingHandlerDiagnostics(compilation, allTypes, handlers, diagnostics);

        var localHandlers = handlers
            .OrderBy(handler => handler.SortKey, StringComparer.Ordinal)
            .ToImmutableArray();
        var dispatchHandlers = ImmutableArray.CreateBuilder<HandlerModel>();
        dispatchHandlers.AddRange(localHandlers);

        if (dispatcherAttribute is not null)
        {
            AddReferencedHandlers(
                compilation,
                queryHandler,
                commandHandler,
                commandWithoutResponseHandler,
                notificationHandler,
                dispatchHandlers,
                diagnostics,
                cancellationToken);
            AddDuplicateDiagnostics(dispatchHandlers, diagnostics);
        }
        else
        {
            AddDuplicateDiagnostics(localHandlers, diagnostics);
        }

        return new GenerationResult(
            methodName,
            dispatcherMethodName,
            localHandlers,
            dispatchHandlers.OrderBy(handler => handler.SortKey, StringComparer.Ordinal).ToImmutableArray(),
            diagnostics.ToImmutable(),
            compilation.AssemblyName ?? "DispatcherModule");
    }

    private static void AddReferencedHandlers(
        Compilation compilation,
        INamedTypeSymbol queryHandler,
        INamedTypeSymbol commandHandler,
        INamedTypeSymbol commandWithoutResponseHandler,
        INamedTypeSymbol notificationHandler,
        ImmutableArray<HandlerModel>.Builder handlers,
        ImmutableArray<Diagnostic>.Builder diagnostics,
        CancellationToken cancellationToken)
    {
        foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols
                     .Where(HasGeneratedHandlerRegistration))
        {
            foreach (var type in GetAllTypes(assembly.GlobalNamespace))
            {
                cancellationToken.ThrowIfCancellationRequested();

                foreach (var handlerInterface in type.AllInterfaces.Where(@interface =>
                             IsHandlerInterface(
                                 @interface.OriginalDefinition,
                                 queryHandler,
                                 commandHandler,
                                 commandWithoutResponseHandler,
                                 notificationHandler)))
                {
                    if (type.Arity != 0 || ContainsTypeParameter(handlerInterface))
                    {
                        continue;
                    }

                    var model = CreateHandlerModel(
                        type,
                        handlerInterface,
                        queryHandler,
                        commandHandler,
                        commandWithoutResponseHandler);
                    if (!compilation.IsSymbolAccessibleWithin(model.MessageType, compilation.Assembly) ||
                        model.ResponseType is not null &&
                        !compilation.IsSymbolAccessibleWithin(model.ResponseType, compilation.Assembly))
                    {
                        diagnostics.Add(Diagnostic.Create(
                            InaccessibleReferencedMessage,
                            Location.None,
                            model.MessageType.ToDisplayString(TypeDisplayFormat),
                            assembly.Name));
                        continue;
                    }

                    handlers.Add(model);
                }
            }
        }
    }

    private static bool HasGeneratedHandlerRegistration(IAssemblySymbol assembly) =>
        assembly.GetAttributes().Any(attribute =>
            attribute.AttributeClass?.ToDisplayString() ==
            "Dispatcher.GenerateDispatcherHandlersAttribute");

    private static HandlerModel CreateHandlerModel(
        INamedTypeSymbol implementation,
        INamedTypeSymbol handlerInterface,
        INamedTypeSymbol queryHandler,
        INamedTypeSymbol commandHandler,
        INamedTypeSymbol commandWithoutResponseHandler)
    {
        var definition = handlerInterface.OriginalDefinition;
        var kind = SymbolEqualityComparer.Default.Equals(definition, queryHandler)
            ? HandlerModelKind.Query
            : SymbolEqualityComparer.Default.Equals(definition, commandHandler)
                ? HandlerModelKind.CommandWithResponse
                : SymbolEqualityComparer.Default.Equals(definition, commandWithoutResponseHandler)
                    ? HandlerModelKind.Command
                    : HandlerModelKind.Notification;

        return new HandlerModel(
            kind,
            handlerInterface.TypeArguments[0],
            handlerInterface.TypeArguments.Length == 2 ? handlerInterface.TypeArguments[1] : null,
            implementation);
    }

    private static void AddDuplicateDiagnostics(
        IEnumerable<HandlerModel> handlers,
        ImmutableArray<Diagnostic>.Builder diagnostics)
    {
        foreach (var group in handlers
                     .Where(handler => handler.Kind != HandlerModelKind.Notification)
                     .GroupBy(handler => handler.MessageType, SymbolEqualityComparer.Default)
                     .Where(group => group.Count() > 1))
        {
            var implementations = string.Join(
                ", ",
                group.Select(handler => handler.ImplementationType.ToDisplayString(TypeDisplayFormat))
                    .OrderBy(name => name, StringComparer.Ordinal));
            diagnostics.Add(Diagnostic.Create(
                DuplicateRequestHandler,
                group.Key!.Locations.FirstOrDefault(),
                group.Key.ToDisplayString(TypeDisplayFormat),
                implementations));
        }
    }

    private static void AddMissingHandlerDiagnostics(
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol> allTypes,
        ImmutableArray<HandlerModel>.Builder handlers,
        ImmutableArray<Diagnostic>.Builder diagnostics)
    {
        var query = compilation.GetTypeByMetadataName(QueryMetadataName);
        var command = compilation.GetTypeByMetadataName(CommandMetadataName);
        var commandWithoutResponse = compilation.GetTypeByMetadataName(CommandWithoutResponseMetadataName);
        if (query is null || command is null || commandWithoutResponse is null)
        {
            return;
        }

        foreach (var type in allTypes.Where(type =>
                     type.Locations.Any(location => location.IsInSource) &&
                     type.Arity == 0 &&
                     !type.IsAbstract &&
                     IsRequest(type, query, command, commandWithoutResponse)))
        {
            if (handlers.Any(handler => SymbolEqualityComparer.Default.Equals(handler.MessageType, type)))
            {
                continue;
            }

            diagnostics.Add(Diagnostic.Create(
                MissingRequestHandler,
                type.Locations.FirstOrDefault(),
                type.ToDisplayString(TypeDisplayFormat)));
        }
    }

    private static bool IsRequest(
        INamedTypeSymbol type,
        INamedTypeSymbol query,
        INamedTypeSymbol command,
        INamedTypeSymbol commandWithoutResponse) =>
        type.AllInterfaces.Any(@interface =>
            SymbolEqualityComparer.Default.Equals(@interface.OriginalDefinition, query) ||
            SymbolEqualityComparer.Default.Equals(@interface.OriginalDefinition, command) ||
            SymbolEqualityComparer.Default.Equals(@interface, commandWithoutResponse));

    private static bool IsHandlerInterface(
        INamedTypeSymbol definition,
        INamedTypeSymbol queryHandler,
        INamedTypeSymbol commandHandler,
        INamedTypeSymbol commandWithoutResponseHandler,
        INamedTypeSymbol notificationHandler) =>
        SymbolEqualityComparer.Default.Equals(definition, queryHandler) ||
        SymbolEqualityComparer.Default.Equals(definition, commandHandler) ||
        SymbolEqualityComparer.Default.Equals(definition, commandWithoutResponseHandler) ||
        SymbolEqualityComparer.Default.Equals(definition, notificationHandler);

    private static bool ContainsTypeParameter(INamedTypeSymbol type) =>
        type.TypeArguments.Any(argument => argument.TypeKind == TypeKind.TypeParameter);

    private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol @namespace)
    {
        foreach (var type in @namespace.GetTypeMembers())
        {
            foreach (var nestedType in GetTypeAndNestedTypes(type))
            {
                yield return nestedType;
            }
        }

        foreach (var childNamespace in @namespace.GetNamespaceMembers())
        {
            foreach (var type in GetAllTypes(childNamespace))
            {
                yield return type;
            }
        }
    }

    private static IEnumerable<INamedTypeSymbol> GetTypeAndNestedTypes(INamedTypeSymbol type)
    {
        yield return type;

        foreach (var nestedType in type.GetTypeMembers())
        {
            foreach (var descendant in GetTypeAndNestedTypes(nestedType))
            {
                yield return descendant;
            }
        }
    }

    private static void Emit(SourceProductionContext context, GenerationResult result)
    {
        foreach (var diagnostic in result.Diagnostics)
        {
            context.ReportDiagnostic(diagnostic);
        }

        if (result.Diagnostics.Any(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error))
        {
            return;
        }

        if (result.MethodName is not null)
        {
            EmitRegistration(context, result);
        }

        if (result.DispatcherMethodName is not null)
        {
            EmitDispatcher(context, result);
        }
    }

    private static void EmitRegistration(SourceProductionContext context, GenerationResult result)
    {
        var className = SanitizeIdentifier(result.AssemblyName) + "DispatcherGeneratedExtensions";
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("namespace Microsoft.Extensions.DependencyInjection;");
        source.AppendLine();
        source.Append("public static class ").Append(className).AppendLine();
        source.AppendLine("{");
        source.Append("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection ")
            .Append(result.MethodName)
            .AppendLine("(");
        source.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(services);");

        foreach (var handler in result.LocalHandlers)
        {
            source.Append("        AddHandler(services, typeof(")
                .Append(handler.ServiceType).Append("), typeof(")
                .Append(handler.ImplementationType.ToDisplayString(TypeDisplayFormat)).AppendLine("));");
        }

        source.AppendLine();
        source.AppendLine("        return services;");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static void AddHandler(");
        source.AppendLine("        global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        source.AppendLine("        global::System.Type serviceType,");
        source.AppendLine("        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(");
        source.AppendLine("            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]");
        source.AppendLine("        global::System.Type implementationType)");
        source.AppendLine("    {");
        source.AppendLine("        foreach (var descriptor in services)");
        source.AppendLine("        {");
        source.AppendLine("            if (descriptor.ServiceType == serviceType && descriptor.ImplementationType == implementationType)");
        source.AppendLine("            {");
        source.AppendLine("                return;");
        source.AppendLine("            }");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Scoped(");
        source.AppendLine("            serviceType, implementationType));");
        source.AppendLine("    }");
        source.AppendLine("}");

        context.AddSource(className + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static void EmitDispatcher(SourceProductionContext context, GenerationResult result)
    {
        const string className = "Dispatcher";
        var generatedNamespace = SanitizeNamespace(result.AssemblyName);
        var generatedTypeName = "global::" + generatedNamespace + "." + className;
        var queries = result.DispatchHandlers.Where(handler => handler.Kind == HandlerModelKind.Query).ToArray();
        var responseCommands = result.DispatchHandlers
            .Where(handler => handler.Kind == HandlerModelKind.CommandWithResponse)
            .ToArray();
        var commands = result.DispatchHandlers.Where(handler => handler.Kind == HandlerModelKind.Command).ToArray();
        var notifications = result.DispatchHandlers
            .Where(handler => handler.Kind == HandlerModelKind.Notification)
            .GroupBy(handler => handler.MessageType, SymbolEqualityComparer.Default)
            .Select(group => group.First())
            .ToArray();
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using global::System.Collections.Frozen;");
        source.AppendLine();
        source.Append("namespace ").Append(generatedNamespace).AppendLine(";");
        source.AppendLine();
        source.Append("internal sealed class ").Append(className).AppendLine(" : global::Dispatcher.IDispatcher");
        source.AppendLine("{");
        source.AppendLine("    private readonly global::System.IServiceProvider serviceProvider;");
        AppendRequestDictionary(source, generatedTypeName, "QueryHandlers", queries, "global::Dispatcher.IQuery", "QueryCore");
        AppendRequestDictionary(source, generatedTypeName, "ResponseCommandHandlers", responseCommands, "global::Dispatcher.ICommand", "ResponseCommandCore");
        AppendCommandDictionary(source, generatedTypeName, commands);
        AppendNotificationDictionary(source, generatedTypeName, notifications);
        source.AppendLine();
        source.Append("    public ").Append(className)
            .AppendLine("(global::System.IServiceProvider serviceProvider)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(serviceProvider);");
        source.AppendLine("        this.serviceProvider = serviceProvider;");
        source.AppendLine("    }");
        AppendDispatcherMethods(source, generatedTypeName);
        AppendCoreMethods(source);
        source.AppendLine("}");
        context.AddSource(className + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));

        const string extensionsName = "DispatcherServiceCollectionExtensions";
        var registration = new StringBuilder();
        registration.AppendLine("// <auto-generated />");
        registration.AppendLine("#nullable enable");
        registration.AppendLine();
        registration.AppendLine("namespace Microsoft.Extensions.DependencyInjection;");
        registration.AppendLine();
        registration.Append("public static class ").Append(extensionsName).AppendLine();
        registration.AppendLine("{");
        registration.Append("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection ")
            .Append(result.DispatcherMethodName).AppendLine("(");
        registration.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        registration.AppendLine("    {");
        registration.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(services);");
        registration.AppendLine("        foreach (var descriptor in services)");
        registration.AppendLine("        {");
        registration.Append("            if (descriptor.ServiceType == typeof(").Append(generatedTypeName).AppendLine("))");
        registration.AppendLine("            {");
        registration.AppendLine("                return services;");
        registration.AppendLine("            }");
        registration.AppendLine("        }");
        registration.AppendLine();
        registration.Append("        services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Scoped(typeof(")
            .Append(generatedTypeName).Append("), typeof(").Append(generatedTypeName).AppendLine(")));");
        AppendDispatcherContractRegistration(registration, "global::Dispatcher.IDispatcher", generatedTypeName);
        AppendDispatcherContractRegistration(registration, "global::Dispatcher.IQueryDispatcher", generatedTypeName);
        AppendDispatcherContractRegistration(registration, "global::Dispatcher.ICommandDispatcher", generatedTypeName);
        AppendDispatcherContractRegistration(registration, "global::Dispatcher.INotificationDispatcher", generatedTypeName);
        registration.AppendLine();
        registration.AppendLine("        return services;");
        registration.AppendLine("    }");
        registration.AppendLine("}");
        context.AddSource(extensionsName + ".g.cs", SourceText.From(registration.ToString(), Encoding.UTF8));
    }

    private static void AppendRequestDictionary(
        StringBuilder source,
        string generatedTypeName,
        string fieldName,
        IEnumerable<HandlerModel> handlers,
        string messageInterface,
        string coreMethod)
    {
        source.AppendLine();
        source.Append("    private static readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type, (global::System.Type ResponseType, object Handler)> ")
            .Append(fieldName).AppendLine(" =");
        source.AppendLine("        new global::System.Collections.Generic.Dictionary<global::System.Type, (global::System.Type ResponseType, object Handler)>");
        source.AppendLine("        {");
        foreach (var handler in handlers)
        {
            var message = handler.MessageType.ToDisplayString(TypeDisplayFormat);
            var response = handler.ResponseType!.ToDisplayString(TypeDisplayFormat);
            source.Append("            [typeof(").Append(message).Append(")] = (typeof(").Append(response)
                .Append("), (global::System.Func<")
                .Append(generatedTypeName)
                .Append(", ").Append(messageInterface).Append('<').Append(response)
                .Append(">, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask<")
                .Append(response).Append(">>)(").AppendLine();
            source.Append("                static (dispatcher, message, token) => dispatcher.")
                .Append(coreMethod).Append("<").Append(message).Append(", ").Append(response)
                .Append(">((").Append(message).AppendLine(")message, token))),");
        }
        source.AppendLine("        }.ToFrozenDictionary();");
    }

    private static void AppendCommandDictionary(
        StringBuilder source,
        string generatedTypeName,
        IEnumerable<HandlerModel> handlers)
    {
        source.AppendLine();
        source.AppendLine("    private static readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type,");
        source.Append("        global::System.Func<").Append(generatedTypeName)
            .AppendLine(", global::Dispatcher.ICommand, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask>> CommandHandlers =");
        source.AppendLine("        new global::System.Collections.Generic.Dictionary<global::System.Type,");
        source.Append("            global::System.Func<").Append(generatedTypeName)
            .AppendLine(", global::Dispatcher.ICommand, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask>>");
        source.AppendLine("        {");
        foreach (var handler in handlers)
        {
            var message = handler.MessageType.ToDisplayString(TypeDisplayFormat);
            source.Append("            [typeof(").Append(message).Append(")] = static (dispatcher, command, token) => dispatcher.CommandCore<")
                .Append(message).Append(">((").Append(message).AppendLine(")command, token),");
        }
        source.AppendLine("        }.ToFrozenDictionary();");
    }

    private static void AppendNotificationDictionary(
        StringBuilder source,
        string generatedTypeName,
        IEnumerable<HandlerModel> handlers)
    {
        source.AppendLine();
        source.AppendLine("    private static readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type,");
        source.Append("        global::System.Func<").Append(generatedTypeName)
            .AppendLine(", global::Dispatcher.INotification, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask>> NotificationHandlers =");
        source.AppendLine("        new global::System.Collections.Generic.Dictionary<global::System.Type,");
        source.Append("            global::System.Func<").Append(generatedTypeName)
            .AppendLine(", global::Dispatcher.INotification, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask>>");
        source.AppendLine("        {");
        foreach (var handler in handlers)
        {
            var message = handler.MessageType.ToDisplayString(TypeDisplayFormat);
            source.Append("            [typeof(").Append(message).Append(")] = static (dispatcher, notification, token) => dispatcher.NotificationCore<")
                .Append(message).Append(">((").Append(message).AppendLine(")notification, token),");
        }
        source.AppendLine("        }.ToFrozenDictionary();");
    }

    private static void AppendDispatcherMethods(StringBuilder source, string generatedTypeName)
    {
        source.AppendLine();
        source.AppendLine("    public global::System.Threading.Tasks.ValueTask<TResponse> QueryAsync<TResponse>(");
        source.AppendLine("        global::Dispatcher.IQuery<TResponse> query,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(query);");
        source.AppendLine("        if (!QueryHandlers.TryGetValue(query.GetType(), out var entry))");
        source.AppendLine("        {");
        source.AppendLine("            throw new global::Dispatcher.HandlerNotFoundException(query.GetType());");
        source.AppendLine("        }");
        source.AppendLine("        if (entry.ResponseType != typeof(TResponse))");
        source.AppendLine("        {");
        source.AppendLine("            throw new global::System.InvalidOperationException($\"The generated handler shape does not match message type '{query.GetType().FullName}'.\");");
        source.AppendLine("        }");
        source.Append("        return global::System.Runtime.CompilerServices.Unsafe.As<global::System.Func<")
            .Append(generatedTypeName).AppendLine(", global::Dispatcher.IQuery<TResponse>, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask<TResponse>>>(entry.Handler)(this, query, cancellationToken);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public global::System.Threading.Tasks.ValueTask<TResponse> ExecuteAsync<TResponse>(");
        source.AppendLine("        global::Dispatcher.ICommand<TResponse> command,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(command);");
        source.AppendLine("        if (!ResponseCommandHandlers.TryGetValue(command.GetType(), out var entry))");
        source.AppendLine("        {");
        source.AppendLine("            throw new global::Dispatcher.HandlerNotFoundException(command.GetType());");
        source.AppendLine("        }");
        source.AppendLine("        if (entry.ResponseType != typeof(TResponse))");
        source.AppendLine("        {");
        source.AppendLine("            throw new global::System.InvalidOperationException($\"The generated handler shape does not match message type '{command.GetType().FullName}'.\");");
        source.AppendLine("        }");
        source.Append("        return global::System.Runtime.CompilerServices.Unsafe.As<global::System.Func<")
            .Append(generatedTypeName).AppendLine(", global::Dispatcher.ICommand<TResponse>, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask<TResponse>>>(entry.Handler)(this, command, cancellationToken);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public global::System.Threading.Tasks.ValueTask ExecuteAsync(");
        source.AppendLine("        global::Dispatcher.ICommand command,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(command);");
        source.AppendLine("        return CommandHandlers.TryGetValue(command.GetType(), out var handler)");
        source.AppendLine("            ? handler(this, command, cancellationToken)");
        source.AppendLine("            : global::System.Threading.Tasks.ValueTask.FromException(");
        source.AppendLine("                new global::Dispatcher.HandlerNotFoundException(command.GetType()));");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public global::System.Threading.Tasks.ValueTask PublishAsync<TNotification>(");
        source.AppendLine("        TNotification notification,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        source.AppendLine("        where TNotification : global::Dispatcher.INotification");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(notification);");
        source.AppendLine("        return NotificationHandlers.TryGetValue(notification.GetType(), out var handler)");
        source.AppendLine("            ? handler(this, notification, cancellationToken)");
        source.AppendLine("            : global::System.Threading.Tasks.ValueTask.CompletedTask;");
        source.AppendLine("    }");
    }

    private static void AppendCoreMethods(StringBuilder source)
    {
        source.AppendLine();
        source.AppendLine("    private global::System.Threading.Tasks.ValueTask<TResponse> QueryCore<TQuery, TResponse>(");
        source.AppendLine("        TQuery query, global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TQuery : global::Dispatcher.IQuery<TResponse> =>");
        source.AppendLine("        RequestCore<TQuery, TResponse>(query, GetRequiredService<global::Dispatcher.IQueryHandler<TQuery, TResponse>>(), cancellationToken);");
        source.AppendLine();
        source.AppendLine("    private global::System.Threading.Tasks.ValueTask<TResponse> ResponseCommandCore<TCommand, TResponse>(");
        source.AppendLine("        TCommand command, global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TCommand : global::Dispatcher.ICommand<TResponse> =>");
        source.AppendLine("        RequestCore<TCommand, TResponse>(command, GetRequiredService<global::Dispatcher.ICommandHandler<TCommand, TResponse>>(), cancellationToken);");
        source.AppendLine();
        source.AppendLine("    private global::System.Threading.Tasks.ValueTask<TResponse> RequestCore<TRequest, TResponse>(");
        source.AppendLine("        TRequest request,");
        source.AppendLine("        global::Dispatcher.IQueryHandler<TRequest, TResponse> handler,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TRequest : global::Dispatcher.IQuery<TResponse> =>");
        source.AppendLine("        RunPipeline(request, token => handler.HandleAsync(request, token), cancellationToken);");
        source.AppendLine();
        source.AppendLine("    private global::System.Threading.Tasks.ValueTask<TResponse> RequestCore<TRequest, TResponse>(");
        source.AppendLine("        TRequest request,");
        source.AppendLine("        global::Dispatcher.ICommandHandler<TRequest, TResponse> handler,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TRequest : global::Dispatcher.ICommand<TResponse> =>");
        source.AppendLine("        RunPipeline(request, token => handler.HandleAsync(request, token), cancellationToken);");
        source.AppendLine();
        source.AppendLine("    private global::System.Threading.Tasks.ValueTask<TResponse> RunPipeline<TRequest, TResponse>(");
        source.AppendLine("        TRequest request,");
        source.AppendLine("        global::Dispatcher.RequestHandlerDelegate<TResponse> handler,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TRequest : global::Dispatcher.IRequest");
        source.AppendLine("    {");
        source.AppendLine("        var behaviors = GetServices<global::Dispatcher.IPipelineBehavior<TRequest, TResponse>>();");
        source.AppendLine("        if (behaviors.Count == 0)");
        source.AppendLine("        {");
        source.AppendLine("            return handler(cancellationToken);");
        source.AppendLine("        }");
        source.AppendLine("        global::Dispatcher.RequestHandlerDelegate<TResponse> pipeline = handler;");
        source.AppendLine("        for (var index = behaviors.Count - 1; index >= 1; index--)");
        source.AppendLine("        {");
        source.AppendLine("            var behavior = behaviors[index];");
        source.AppendLine("            var next = pipeline;");
        source.AppendLine("            pipeline = token => behavior.HandleAsync(request, next, token);");
        source.AppendLine("        }");
        source.AppendLine("        return behaviors[0].HandleAsync(request, pipeline, cancellationToken);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private global::System.Threading.Tasks.ValueTask CommandCore<TCommand>(");
        source.AppendLine("        TCommand command, global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TCommand : global::Dispatcher.ICommand");
        source.AppendLine("    {");
        source.AppendLine("        var handler = GetRequiredService<global::Dispatcher.ICommandHandler<TCommand>>();");
        source.AppendLine("        var behaviors = GetServices<global::Dispatcher.IPipelineBehavior<TCommand, global::Dispatcher.Unit>>();");
        source.AppendLine("        if (behaviors.Count == 0)");
        source.AppendLine("        {");
        source.AppendLine("            return handler.HandleAsync(command, cancellationToken);");
        source.AppendLine("        }");
        source.AppendLine("        return RunCommandPipeline(command, handler, behaviors, cancellationToken);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static async global::System.Threading.Tasks.ValueTask RunCommandPipeline<TCommand>(");
        source.AppendLine("        TCommand command,");
        source.AppendLine("        global::Dispatcher.ICommandHandler<TCommand> handler,");
        source.AppendLine("        global::System.Collections.Generic.IReadOnlyList<global::Dispatcher.IPipelineBehavior<TCommand, global::Dispatcher.Unit>> behaviors,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TCommand : global::Dispatcher.ICommand");
        source.AppendLine("    {");
        source.AppendLine("        global::Dispatcher.RequestHandlerDelegate<global::Dispatcher.Unit> pipeline = async token =>");
        source.AppendLine("        {");
        source.AppendLine("            await handler.HandleAsync(command, token).ConfigureAwait(false);");
        source.AppendLine("            return global::Dispatcher.Unit.Value;");
        source.AppendLine("        };");
        source.AppendLine("        for (var index = behaviors.Count - 1; index >= 1; index--)");
        source.AppendLine("        {");
        source.AppendLine("            var behavior = behaviors[index];");
        source.AppendLine("            var next = pipeline;");
        source.AppendLine("            pipeline = token => behavior.HandleAsync(command, next, token);");
        source.AppendLine("        }");
        source.AppendLine("        await behaviors[0].HandleAsync(command, pipeline, cancellationToken).ConfigureAwait(false);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private async global::System.Threading.Tasks.ValueTask NotificationCore<TNotification>(");
        source.AppendLine("        TNotification notification, global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("        where TNotification : global::Dispatcher.INotification");
        source.AppendLine("    {");
        source.AppendLine("        foreach (var handler in GetServices<global::Dispatcher.INotificationHandler<TNotification>>())");
        source.AppendLine("        {");
        source.AppendLine("            await handler.HandleAsync(notification, cancellationToken).ConfigureAwait(false);");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private T GetRequiredService<T>() where T : notnull =>");
        source.AppendLine("        (T?)serviceProvider.GetService(typeof(T)) ??");
        source.AppendLine("        throw new global::System.InvalidOperationException($\"Service '{typeof(T).FullName}' is not registered.\");");
        source.AppendLine();
        source.AppendLine("    private global::System.Collections.Generic.IReadOnlyList<T> GetServices<T>()");
        source.AppendLine("    {");
        source.AppendLine("        var services = (global::System.Collections.Generic.IEnumerable<T>?)serviceProvider.GetService(");
        source.AppendLine("            typeof(global::System.Collections.Generic.IEnumerable<T>));");
        source.AppendLine("        return services switch");
        source.AppendLine("        {");
        source.AppendLine("            null => [],");
        source.AppendLine("            global::System.Collections.Generic.IReadOnlyList<T> list => list,");
        source.AppendLine("            _ => global::System.Linq.Enumerable.ToArray(services)");
        source.AppendLine("        };");
        source.AppendLine("    }");
    }

    private static void AppendDispatcherContractRegistration(
        StringBuilder source,
        string contractType,
        string generatedTypeName)
    {
        source.Append("        services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Scoped(typeof(")
            .Append(contractType).AppendLine("), static provider =>");
        source.Append("            provider.GetService(typeof(").Append(generatedTypeName).AppendLine(")) ??");
        source.Append("            throw new global::System.InvalidOperationException(\"Service '")
            .Append(generatedTypeName).AppendLine("' is not registered.\")));");
    }

    private static string SanitizeNamespace(string value)
    {
        var segments = value.Split('.');

        for (var index = 0; index < segments.Length; index++)
        {
            segments[index] = SanitizeIdentifier(segments[index]);
        }

        return string.Join(".", segments);
    }

    private static string SanitizeIdentifier(string value)
    {
        var builder = new StringBuilder(value.Length + 1);
        if (value.Length == 0 || !SyntaxFacts.IsIdentifierStartCharacter(value[0]))
        {
            builder.Append('_');
        }

        foreach (var character in value)
        {
            builder.Append(SyntaxFacts.IsIdentifierPartCharacter(character) ? character : '_');
        }

        return builder.ToString();
    }

    private enum HandlerModelKind
    {
        Query,
        CommandWithResponse,
        Command,
        Notification
    }

    private sealed class HandlerModel
    {
        public HandlerModel(
            HandlerModelKind kind,
            ITypeSymbol messageType,
            ITypeSymbol? responseType,
            INamedTypeSymbol implementationType)
        {
            Kind = kind;
            MessageType = messageType;
            ResponseType = responseType;
            ImplementationType = implementationType;
        }

        public HandlerModelKind Kind { get; }
        public ITypeSymbol MessageType { get; }
        public ITypeSymbol? ResponseType { get; }
        public INamedTypeSymbol ImplementationType { get; }
        public string SortKey => MessageType.ToDisplayString(TypeDisplayFormat) + "|" +
            ImplementationType.ToDisplayString(TypeDisplayFormat);
        public string ServiceType => Kind switch
        {
            HandlerModelKind.Query => "global::Dispatcher.IQueryHandler<" +
                MessageType.ToDisplayString(TypeDisplayFormat) + ", " +
                ResponseType!.ToDisplayString(TypeDisplayFormat) + ">",
            HandlerModelKind.CommandWithResponse => "global::Dispatcher.ICommandHandler<" +
                MessageType.ToDisplayString(TypeDisplayFormat) + ", " +
                ResponseType!.ToDisplayString(TypeDisplayFormat) + ">",
            HandlerModelKind.Command => "global::Dispatcher.ICommandHandler<" +
                MessageType.ToDisplayString(TypeDisplayFormat) + ">",
            _ => "global::Dispatcher.INotificationHandler<" +
                MessageType.ToDisplayString(TypeDisplayFormat) + ">"
        };
    }

    private sealed class GenerationResult
    {
        public static readonly GenerationResult Empty = new(
            null,
            null,
            ImmutableArray<HandlerModel>.Empty,
            ImmutableArray<HandlerModel>.Empty,
            ImmutableArray<Diagnostic>.Empty);

        public GenerationResult(
            string? methodName,
            string? dispatcherMethodName,
            ImmutableArray<HandlerModel> localHandlers,
            ImmutableArray<HandlerModel> dispatchHandlers,
            ImmutableArray<Diagnostic> diagnostics,
            string assemblyName = "")
        {
            MethodName = methodName;
            DispatcherMethodName = dispatcherMethodName;
            LocalHandlers = localHandlers;
            DispatchHandlers = dispatchHandlers;
            Diagnostics = diagnostics;
            AssemblyName = assemblyName;
        }

        public string? MethodName { get; }
        public string? DispatcherMethodName { get; }
        public ImmutableArray<HandlerModel> LocalHandlers { get; }
        public ImmutableArray<HandlerModel> DispatchHandlers { get; }
        public ImmutableArray<Diagnostic> Diagnostics { get; }
        public string AssemblyName { get; }
    }
}