namespace Dispatcher.SourceGeneration;

internal static class InjectedSources
{
    internal const string HandlerAttribute = """
        // <auto-generated />
        #nullable enable
    
        namespace Dispatcher;
    
        [global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]
        internal sealed class GenerateDispatcherHandlersAttribute : global::System.Attribute
        {
            public GenerateDispatcherHandlersAttribute(string methodName)
            {
                MethodName = methodName;
            }
    
            public string MethodName { get; }
        }
        """;
    
    internal const string DispatcherAttribute = """
        // <auto-generated />
        #nullable enable
    
        namespace Dispatcher;
    
        [global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]
        internal sealed class GenerateDispatcherAttribute : global::System.Attribute
        {
            public GenerateDispatcherAttribute(string methodName)
            {
                MethodName = methodName;
            }
    
            public string MethodName { get; }
        }
        """;
    
}
