<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <PackageId>Send0xx.Dispatcher.DependencyInjection</PackageId>
    <Title>Dispatcher dependency injection integration</Title>
    <Description>Microsoft dependency injection integration for the Dispatcher CQRS library with reflection-based handler scanning.</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsAotCompatible>false</IsAotCompatible>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Dispatcher.DependencyInjection.Extensions/Dispatcher.DependencyInjection.Extensions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
