<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <PackageId>Dispatcher.DependencyInjection</PackageId>
    <Description>Reflection-based Microsoft dependency injection integration for Dispatcher.</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsAotCompatible>false</IsAotCompatible>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Dispatcher.Extensions.Microsoft.DependencyInjection/Dispatcher.Extensions.Microsoft.DependencyInjection.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
