using System.Text;
using Dispatcher.SourceGeneration.Model;
using Dispatcher.SourceGeneration.Support;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Dispatcher.SourceGeneration.Emission;

internal static class DispatcherImplementationEmitter
{
    private const string DispatcherType = "global::Dispatcher.SourceGeneration.Dispatcher";

    internal static void Emit(SourceProductionContext output, DispatcherSourceModel model)
    {
        var code = new CodeWriter();
        code.Lines("""
                   // <auto-generated />
                   #nullable enable
                   using global::System.Collections.Frozen;

                   namespace Dispatcher.SourceGeneration;

                   internal sealed class Dispatcher : global::Dispatcher.IDispatcher
                   {
                       private readonly global::System.IServiceProvider serviceProvider;
                   """);
        if (model.UsesOpenNotificationHandlers)
        {
            code.Line(
                "    private readonly global::Dispatcher.SourceGeneration.OpenNotificationHandlerRegistry openNotificationHandlers;");
        }

        WriteResponseHandlerTable(code, "QueryHandlers", model.Queries, "global::Dispatcher.IQuery", "QueryCore");
        WriteResponseHandlerTable(
            code,
            "ResponseCommandHandlers",
            model.ResponseCommands,
            "global::Dispatcher.ICommand",
            "ResponseCommandCore");
        WriteCommandHandlerTable(code, model.Commands);
        WriteNotificationHandlerTable(code, model.Notifications);
        WriteConstructor(code, model.UsesOpenNotificationHandlers);
        WritePublicMethods(code);
        WriteCoreMethods(code, model.UsesOpenNotificationHandlers);
        WriteRouteChecks(code);
        code.Line("}");

        if (model.UsesOpenNotificationHandlers)
        {
            WriteOpenNotificationRegistry(code, model.Notifications);
        }

        TelemetryEmitter.Write(code, model);
        output.AddSource("Dispatcher.g.cs", SourceText.From(code.ToString(), Encoding.UTF8));
    }

    private static void WriteResponseHandlerTable(
        CodeWriter code,
        string fieldName,
        IReadOnlyList<DispatchRoute> routes,
        string messageInterface,
        string coreMethod)
    {
        code.Line();
        code.Lines($$"""
                         private static readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type, (global::System.Type ResponseType, object Handler)> {{fieldName}} =
                             new global::System.Collections.Generic.Dictionary<global::System.Type, (global::System.Type ResponseType, object Handler)>
                             {
                     """);
        foreach (var route in routes)
        {
            var message = CSharpNames.Type(route.MessageType);
            var handledMessage = CSharpNames.Type(route.Handler!.MessageType);
            var response = CSharpNames.Type(route.Handler.ResponseType!);
            code.Line($"            [typeof({message})] = (typeof({response}), " +
                      $"(global::System.Func<{DispatcherType}, {messageInterface}<{response}>, " +
                      "global::System.Threading.CancellationToken, " +
                      $"global::System.Threading.Tasks.ValueTask<{response}>>)(");
            code.Line($"                static (dispatcher, message, token) => dispatcher.{coreMethod}" +
                      $"<{handledMessage}, {response}>(({handledMessage})message, token))),");
        }

        code.Lines("""
                           }.ToFrozenDictionary();
                   """);
    }

    private static void WriteCommandHandlerTable(CodeWriter code, IReadOnlyList<DispatchRoute> routes)
    {
        code.Line();
        code.Lines($$"""
                         private static readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type,
                             global::System.Func<{{DispatcherType}}, global::Dispatcher.ICommand, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask>> CommandHandlers =
                             new global::System.Collections.Generic.Dictionary<global::System.Type,
                                 global::System.Func<{{DispatcherType}}, global::Dispatcher.ICommand, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask>>
                             {
                     """);
        foreach (var route in routes)
        {
            var message = CSharpNames.Type(route.MessageType);
            var handledMessage = CSharpNames.Type(route.Handler!.MessageType);
            code.Line(
                $"            [typeof({message})] = static (dispatcher, command, token) => dispatcher.CommandCore<{handledMessage}>(({handledMessage})command, token),");
        }

        code.Line("        }.ToFrozenDictionary();");
    }

    private static void WriteNotificationHandlerTable(CodeWriter code, IReadOnlyList<DispatchRoute> routes)
    {
        code.Line();
        code.Lines($$"""
                         private static readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type,
                             global::System.Func<{{DispatcherType}}, global::Dispatcher.INotification, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask>> NotificationHandlers =
                             new global::System.Collections.Generic.Dictionary<global::System.Type,
                                 global::System.Func<{{DispatcherType}}, global::Dispatcher.INotification, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask>>
                             {
                     """);
        foreach (var route in routes)
        {
            var message = CSharpNames.Type(route.MessageType);
            if (route.Handler is null)
            {
                code.Line(
                    $"            [typeof({message})] = static (dispatcher, notification, token) => dispatcher.OpenNotificationCore<{message}>(({message})notification, token),");
                continue;
            }

            var handledMessage = CSharpNames.Type(route.Handler.MessageType);
            if (route.OpenNotificationHandlers.IsDefaultOrEmpty)
            {
                code.Line(
                    $"            [typeof({message})] = static (dispatcher, notification, token) => dispatcher.NotificationCore<{handledMessage}>(({handledMessage})notification, token),");
                continue;
            }

            code.Line(
                $"            [typeof({message})] = static (dispatcher, notification, token) => dispatcher.NotificationCore<{handledMessage}, {message}>(({handledMessage})notification, ({message})notification, token),");
        }

        code.Line("        }.ToFrozenDictionary();");
    }

    private static void WriteConstructor(CodeWriter code, bool usesOpenNotificationHandlers)
    {
        code.Line();
        if (usesOpenNotificationHandlers)
        {
            code.Lines("""
                           public Dispatcher(
                               global::System.IServiceProvider serviceProvider,
                               global::Dispatcher.SourceGeneration.OpenNotificationHandlerRegistry openNotificationHandlers)
                           {
                               global::System.ArgumentNullException.ThrowIfNull(serviceProvider);
                               this.serviceProvider = serviceProvider;
                               this.openNotificationHandlers = openNotificationHandlers;
                           }
                       """);
            return;
        }

        code.Lines("""
                       public Dispatcher(global::System.IServiceProvider serviceProvider)
                       {
                           global::System.ArgumentNullException.ThrowIfNull(serviceProvider);
                           this.serviceProvider = serviceProvider;
                       }
                   """);
    }

    private static void WritePublicMethods(CodeWriter code)
    {
        code.Lines($$"""

                         public global::System.Threading.Tasks.ValueTask<TResponse> QueryAsync<TResponse>(
                             global::Dispatcher.IQuery<TResponse> query,
                             global::System.Threading.CancellationToken cancellationToken = default)
                         {
                             global::System.ArgumentNullException.ThrowIfNull(query);
                             if (!QueryHandlers.TryGetValue(query.GetType(), out var entry))
                             {
                                 throw new global::Dispatcher.HandlerNotFoundException(query.GetType());
                             }
                             if (entry.ResponseType != typeof(TResponse))
                             {
                                 throw new global::System.InvalidOperationException($"The generated handler shape does not match message type '{query.GetType().FullName}'.");
                             }
                             return global::System.Runtime.CompilerServices.Unsafe.As<global::System.Func<{{DispatcherType}}, global::Dispatcher.IQuery<TResponse>, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask<TResponse>>>(entry.Handler)(this, query, cancellationToken);
                         }

                         public global::System.Threading.Tasks.ValueTask<TResponse> ExecuteAsync<TResponse>(
                             global::Dispatcher.ICommand<TResponse> command,
                             global::System.Threading.CancellationToken cancellationToken = default)
                         {
                             global::System.ArgumentNullException.ThrowIfNull(command);
                             if (!ResponseCommandHandlers.TryGetValue(command.GetType(), out var entry))
                             {
                                 throw new global::Dispatcher.HandlerNotFoundException(command.GetType());
                             }
                             if (entry.ResponseType != typeof(TResponse))
                             {
                                 throw new global::System.InvalidOperationException($"The generated handler shape does not match message type '{command.GetType().FullName}'.");
                             }
                             return global::System.Runtime.CompilerServices.Unsafe.As<global::System.Func<{{DispatcherType}}, global::Dispatcher.ICommand<TResponse>, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask<TResponse>>>(entry.Handler)(this, command, cancellationToken);
                         }

                         public global::System.Threading.Tasks.ValueTask ExecuteAsync(
                             global::Dispatcher.ICommand command,
                             global::System.Threading.CancellationToken cancellationToken = default)
                         {
                             global::System.ArgumentNullException.ThrowIfNull(command);
                             if (!CommandHandlers.TryGetValue(command.GetType(), out var handler))
                             {
                                 throw new global::Dispatcher.HandlerNotFoundException(command.GetType());
                             }
                             return handler(this, command, cancellationToken);
                         }

                         public global::System.Threading.Tasks.ValueTask PublishAsync<TNotification>(
                             TNotification notification,
                             global::System.Threading.CancellationToken cancellationToken = default)
                             where TNotification : global::Dispatcher.INotification
                         {
                             global::System.ArgumentNullException.ThrowIfNull(notification);
                             return NotificationHandlers.TryGetValue(notification.GetType(), out var handler)
                                 ? handler(this, notification, cancellationToken)
                                 : global::System.Threading.Tasks.ValueTask.CompletedTask;
                         }
                     """);
    }

    private static void WriteCoreMethods(CodeWriter code, bool usesOpenNotificationHandlers)
    {
        code.Lines("""

                       private global::System.Threading.Tasks.ValueTask<TResponse> QueryCore<TQuery, TResponse>(
                           TQuery query, global::System.Threading.CancellationToken cancellationToken)
                           where TQuery : global::Dispatcher.IQuery<TResponse> =>
                           RequestCore<TQuery, TResponse>(query, GetRequiredService<global::Dispatcher.IQueryHandler<TQuery, TResponse>>(), cancellationToken);

                       private global::System.Threading.Tasks.ValueTask<TResponse> ResponseCommandCore<TCommand, TResponse>(
                           TCommand command, global::System.Threading.CancellationToken cancellationToken)
                           where TCommand : global::Dispatcher.ICommand<TResponse> =>
                           RequestCore<TCommand, TResponse>(command, GetRequiredService<global::Dispatcher.ICommandHandler<TCommand, TResponse>>(), cancellationToken);

                       private global::System.Threading.Tasks.ValueTask<TResponse> RequestCore<TRequest, TResponse>(
                           TRequest request,
                           global::Dispatcher.IQueryHandler<TRequest, TResponse> handler,
                           global::System.Threading.CancellationToken cancellationToken)
                           where TRequest : global::Dispatcher.IQuery<TResponse>
                       {
                           var behaviors = GetServices<global::Dispatcher.IPipelineBehavior<TRequest, TResponse>>();
                           if (behaviors.Count == 0)
                           {
                               return handler.HandleAsync(request, cancellationToken);
                           }
                           return RunQueryPipeline(request, handler, behaviors, cancellationToken);
                       }
                   """);
        if (usesOpenNotificationHandlers)
        {
            code.Lines("""

                           private async global::System.Threading.Tasks.ValueTask NotificationCore<THandledNotification, TNotification>(
                               THandledNotification handledNotification,
                               TNotification notification,
                               global::System.Threading.CancellationToken cancellationToken)
                               where THandledNotification : global::Dispatcher.INotification
                               where TNotification : global::Dispatcher.INotification
                           {
                               var handlers = GetServices<global::Dispatcher.INotificationHandler<THandledNotification>>();
                               for (var index = 0; index < handlers.Count; index++)
                               {
                                   await handlers[index].HandleAsync(handledNotification, cancellationToken).ConfigureAwait(false);
                               }
                               await OpenNotificationCore(notification, cancellationToken).ConfigureAwait(false);
                           }

                           private async global::System.Threading.Tasks.ValueTask OpenNotificationCore<TNotification>(
                               TNotification notification, global::System.Threading.CancellationToken cancellationToken)
                               where TNotification : global::Dispatcher.INotification
                           {
                               var handlers = openNotificationHandlers.GetHandlers(typeof(TNotification));
                               for (var index = 0; index < handlers.Length; index++)
                               {
                                   await handlers[index](serviceProvider, notification, cancellationToken).ConfigureAwait(false);
                               }
                           }
                       """);
        }

        code.Lines("""

                       private global::System.Threading.Tasks.ValueTask<TResponse> RequestCore<TRequest, TResponse>(
                           TRequest request,
                           global::Dispatcher.ICommandHandler<TRequest, TResponse> handler,
                           global::System.Threading.CancellationToken cancellationToken)
                           where TRequest : global::Dispatcher.ICommand<TResponse>
                       {
                           var behaviors = GetServices<global::Dispatcher.IPipelineBehavior<TRequest, TResponse>>();
                           if (behaviors.Count == 0)
                           {
                               return handler.HandleAsync(request, cancellationToken);
                           }
                           return RunResponseCommandPipeline(request, handler, behaviors, cancellationToken);
                       }

                       private static global::System.Threading.Tasks.ValueTask<TResponse> RunQueryPipeline<TRequest, TResponse>(
                           TRequest request,
                           global::Dispatcher.IQueryHandler<TRequest, TResponse> handler,
                           global::System.Collections.Generic.IReadOnlyList<global::Dispatcher.IPipelineBehavior<TRequest, TResponse>> behaviors,
                           global::System.Threading.CancellationToken cancellationToken)
                           where TRequest : global::Dispatcher.IQuery<TResponse>
                       {
                           global::Dispatcher.RequestHandlerDelegate<TResponse> pipeline = token => handler.HandleAsync(request, token);
                           for (var index = behaviors.Count - 1; index >= 1; index--)
                           {
                               var behavior = behaviors[index];
                               var next = pipeline;
                               pipeline = token => behavior.HandleAsync(request, next, token);
                           }
                           return behaviors[0].HandleAsync(request, pipeline, cancellationToken);
                       }

                       private static global::System.Threading.Tasks.ValueTask<TResponse> RunResponseCommandPipeline<TRequest, TResponse>(
                           TRequest request,
                           global::Dispatcher.ICommandHandler<TRequest, TResponse> handler,
                           global::System.Collections.Generic.IReadOnlyList<global::Dispatcher.IPipelineBehavior<TRequest, TResponse>> behaviors,
                           global::System.Threading.CancellationToken cancellationToken)
                           where TRequest : global::Dispatcher.ICommand<TResponse>
                       {
                           global::Dispatcher.RequestHandlerDelegate<TResponse> pipeline = token => handler.HandleAsync(request, token);
                           for (var index = behaviors.Count - 1; index >= 1; index--)
                           {
                               var behavior = behaviors[index];
                               var next = pipeline;
                               pipeline = token => behavior.HandleAsync(request, next, token);
                           }
                           return behaviors[0].HandleAsync(request, pipeline, cancellationToken);
                       }

                       private global::System.Threading.Tasks.ValueTask CommandCore<TCommand>(
                           TCommand command, global::System.Threading.CancellationToken cancellationToken)
                           where TCommand : global::Dispatcher.ICommand
                       {
                           var handler = GetRequiredService<global::Dispatcher.ICommandHandler<TCommand>>();
                           var behaviors = GetServices<global::Dispatcher.IPipelineBehavior<TCommand, global::Dispatcher.Unit>>();
                           if (behaviors.Count == 0)
                           {
                               return handler.HandleAsync(command, cancellationToken);
                           }
                           return RunCommandPipeline(command, handler, behaviors, cancellationToken);
                       }

                       private static async global::System.Threading.Tasks.ValueTask RunCommandPipeline<TCommand>(
                           TCommand command,
                           global::Dispatcher.ICommandHandler<TCommand> handler,
                           global::System.Collections.Generic.IReadOnlyList<global::Dispatcher.IPipelineBehavior<TCommand, global::Dispatcher.Unit>> behaviors,
                           global::System.Threading.CancellationToken cancellationToken)
                           where TCommand : global::Dispatcher.ICommand
                       {
                           global::Dispatcher.RequestHandlerDelegate<global::Dispatcher.Unit> pipeline = async token =>
                           {
                               await handler.HandleAsync(command, token).ConfigureAwait(false);
                               return global::Dispatcher.Unit.Value;
                           };
                           for (var index = behaviors.Count - 1; index >= 1; index--)
                           {
                               var behavior = behaviors[index];
                               var next = pipeline;
                               pipeline = token => behavior.HandleAsync(command, next, token);
                           }
                           await behaviors[0].HandleAsync(command, pipeline, cancellationToken).ConfigureAwait(false);
                       }

                       private async global::System.Threading.Tasks.ValueTask NotificationCore<TNotification>(
                           TNotification notification, global::System.Threading.CancellationToken cancellationToken)
                           where TNotification : global::Dispatcher.INotification
                       {
                           var handlers = GetServices<global::Dispatcher.INotificationHandler<TNotification>>();
                           for (var index = 0; index < handlers.Count; index++)
                           {
                               await handlers[index].HandleAsync(notification, cancellationToken).ConfigureAwait(false);
                           }
                       }

                       private T GetRequiredService<T>() where T : notnull =>
                           (T?)serviceProvider.GetService(typeof(T)) ??
                           throw new global::System.InvalidOperationException($"Service '{typeof(T).FullName}' is not registered.");

                       private global::System.Collections.Generic.IReadOnlyList<T> GetServices<T>()
                       {
                           var services = (global::System.Collections.Generic.IEnumerable<T>?)serviceProvider.GetService(
                               typeof(global::System.Collections.Generic.IEnumerable<T>));
                           return services switch
                           {
                               null => [],
                               global::System.Collections.Generic.IReadOnlyList<T> list => list,
                               _ => global::System.Linq.Enumerable.ToArray(services)
                           };
                       }
                   """);
    }

    private static void WriteRouteChecks(CodeWriter code)
    {
        code.Lines("""

                       internal static bool HasQueryHandler(global::System.Type messageType, global::System.Type responseType) =>
                           QueryHandlers.TryGetValue(messageType, out var entry) && entry.ResponseType == responseType;

                       internal static bool HasResponseCommandHandler(global::System.Type messageType, global::System.Type responseType) =>
                           ResponseCommandHandlers.TryGetValue(messageType, out var entry) && entry.ResponseType == responseType;

                       internal static bool HasCommandHandler(global::System.Type messageType) =>
                           CommandHandlers.ContainsKey(messageType);

                       internal static bool HasNotificationHandlers(global::System.Type messageType) =>
                           NotificationHandlers.ContainsKey(messageType);
                   """);
    }

    private static void WriteOpenNotificationRegistry(CodeWriter code, IReadOnlyList<DispatchRoute> notificationRoutes)
    {
        var routes = notificationRoutes
            .Where(static route => !route.OpenNotificationHandlers.IsDefaultOrEmpty)
            .ToArray();
        code.Lines("""

                   internal delegate global::System.Threading.Tasks.ValueTask OpenNotificationHandlerInvoker(
                       global::System.IServiceProvider serviceProvider,
                       global::Dispatcher.INotification notification,
                       global::System.Threading.CancellationToken cancellationToken);

                   internal sealed class OpenNotificationHandlerRegistry
                   {
                       private readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type,
                           global::Dispatcher.SourceGeneration.OpenNotificationHandlerInvoker[]> handlers;

                       public OpenNotificationHandlerRegistry(
                           global::System.Collections.Generic.IEnumerable<global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor> registrations)
                       {
                   """);
        for (var index = 0; index < routes.Length; index++)
        {
            code.Line(
                $"        var route{index} = new global::System.Collections.Generic.List<global::Dispatcher.SourceGeneration.OpenNotificationHandlerInvoker>();");
        }

        code.Line("        foreach (var registration in registrations)");
        code.Line("        {");
        for (var routeIndex = 0; routeIndex < routes.Length; routeIndex++)
        {
            var route = routes[routeIndex];
            var message = CSharpNames.Type(route.MessageType);
            foreach (var handler in route.OpenNotificationHandlers)
            {
                var names = new OpenHandlerMethodNames(handler);
                code.Line(
                    $"            if ({names.RegistrationClass}.IsOpenNotificationHandler_{names.Suffix}<{message}>(registration))");
                code.Line("            {");
                code.Line(
                    $"                route{routeIndex}.Add(static (provider, notification, token) => {names.RegistrationClass}.InvokeOpenNotificationHandler_{names.Suffix}<{message}>(provider, ({message})notification, token));");
                code.Line("                continue;");
                code.Line("            }");
            }
        }

        code.Lines("""
                           }

                           handlers = new global::System.Collections.Generic.Dictionary<global::System.Type,
                               global::Dispatcher.SourceGeneration.OpenNotificationHandlerInvoker[]>
                           {
                   """);
        for (var routeIndex = 0; routeIndex < routes.Length; routeIndex++)
        {
            code.Line(
                $"            [typeof({CSharpNames.Type(routes[routeIndex].MessageType)})] = route{routeIndex}.ToArray(),");
        }

        code.Lines("""
                           }.ToFrozenDictionary();
                       }

                       internal global::Dispatcher.SourceGeneration.OpenNotificationHandlerInvoker[] GetHandlers(
                           global::System.Type notificationType) =>
                           handlers.TryGetValue(notificationType, out var routeHandlers) ? routeHandlers : [];
                   }
                   """);
    }
}