using System.Text;
using Dispatcher.SourceGeneration.Model;
using Dispatcher.SourceGeneration.Support;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Dispatcher.SourceGeneration.Emission;

internal static class DispatcherRegistrationEmitter
{
    private const string DispatcherType = "global::Dispatcher.SourceGeneration.Dispatcher";

    internal static void Emit(
        SourceProductionContext output,
        GenerationModel generation,
        DispatcherSourceModel dispatcher)
    {
        var method = generation.DispatcherRegistrationMethod!;
        var code = new CodeWriter();
        code.Lines($$"""
                     // <auto-generated />
                     #nullable enable
                     namespace Dispatcher.SourceGeneration;

                     /// <summary>
                     /// Provides registration methods for the source-generated Dispatcher implementation.
                     /// </summary>
                     public static class GeneratedDispatcherServiceCollectionExtensions
                     {
                         /// <summary>
                         /// Registers the source-generated Dispatcher implementation.
                         /// </summary>
                         /// <param name="services">The service collection to add Dispatcher services to.</param>
                         /// <returns>The same service collection so that additional calls can be chained.</returns>
                         /// <exception cref="global::System.ArgumentNullException">
                         /// <paramref name="services"/> is <see langword="null"/>.
                         /// </exception>
                         public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection {{method}}(
                             this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                             => {{method}}(services, static _ => { });

                         /// <summary>
                         /// Registers the source-generated Dispatcher implementation using the specified options.
                         /// </summary>
                         /// <param name="services">The service collection to add Dispatcher services to.</param>
                         /// <param name="configure">The delegate that configures Dispatcher services.</param>
                         /// <returns>The same service collection so that additional calls can be chained.</returns>
                         /// <exception cref="global::System.ArgumentNullException">
                         /// <paramref name="services"/> or <paramref name="configure"/> is <see langword="null"/>.
                         /// </exception>
                         /// <exception cref="global::System.ArgumentOutOfRangeException">
                         /// <paramref name="configure"/> sets the Dispatcher service lifetime to singleton.
                         /// </exception>
                         public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection {{method}}(
                             this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
                             global::System.Action<global::Dispatcher.DispatcherOptions> configure)
                         {
                             global::System.ArgumentNullException.ThrowIfNull(services);
                             global::System.ArgumentNullException.ThrowIfNull(configure);
                             var options = new global::Dispatcher.DispatcherOptions();
                             configure(options);
                             if (options.ServiceLifetime == global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton)
                             {
                                 throw new global::System.ArgumentOutOfRangeException(
                                     nameof(configure),
                                     options.ServiceLifetime,
                                     "A singleton dispatcher would capture the root service provider.");
                             }
                     """);
        WriteOpenHandlerRouteRegistration(code, dispatcher);
        WritePendingOpenHandlerRegistration(code, dispatcher);
        WriteIdempotenceCheck(code);
        WriteImplementationRegistration(code, dispatcher.UsesOpenNotificationHandlers);
        WriteTelemetryRegistration(code);
        code.Line("        return services;");
        code.Line("    }");
        code.Line("}");
        output.AddSource(
            "GeneratedDispatcherServiceCollectionExtensions.g.cs",
            SourceText.From(code.ToString(), Encoding.UTF8));
    }

    private static void WriteOpenHandlerRouteRegistration(CodeWriter code, DispatcherSourceModel dispatcher)
    {
        foreach (var route in dispatcher.Notifications.Where(static route =>
                     !route.OpenNotificationHandlers.IsDefaultOrEmpty))
        {
            var message = CSharpNames.Type(route.MessageType);
            foreach (var handler in route.OpenNotificationHandlers)
            {
                var names = new OpenHandlerMethodNames(handler);
                code.Line(
                    $"        {names.RegistrationClass}.RegisterOpenNotificationHandler_{names.Suffix}<{message}>(services);");
            }
        }
    }

    private static void WritePendingOpenHandlerRegistration(CodeWriter code, DispatcherSourceModel dispatcher)
    {
        if (!dispatcher.UsesOpenNotificationHandlers)
        {
            return;
        }

        code.Lines("""

                           var openNotificationRegistrationCount = services.Count;
                           for (var index = 0; index < openNotificationRegistrationCount; index++)
                           {
                               var descriptor = services[index];
                   """);
        foreach (var handler in dispatcher.RoutedOpenHandlers)
        {
            var names = new OpenHandlerMethodNames(handler);
            code.Line($"            if ({names.RegistrationClass}." +
                      $"RegisterPendingOpenNotificationHandler_{names.Suffix}(descriptor, services))");
            code.Line("            {");
            code.Line("                continue;");
            code.Line("            }");
        }

        code.Line("        }");
    }

    private static void WriteIdempotenceCheck(CodeWriter code)
    {
        code.Lines($$"""

                             foreach (var descriptor in services)
                             {
                                 if (descriptor.ServiceType == typeof({{DispatcherType}}))
                                 {
                                     return services;
                                 }
                             }
                     """);
    }

    private static void WriteImplementationRegistration(CodeWriter code, bool usesOpenNotificationHandlers)
    {
        if (usesOpenNotificationHandlers)
        {
            code.Line();
            code.Line(
                "        services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton(");
            code.Line("            typeof(global::Dispatcher.SourceGeneration.OpenNotificationHandlerRegistry),");
            code.Line(
                "            _ => new global::Dispatcher.SourceGeneration.OpenNotificationHandlerRegistry(services)));");
        }

        code.Lines($$"""
                             services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(
                                 typeof({{DispatcherType}}),
                                 typeof({{DispatcherType}}),
                                 options.ServiceLifetime));
                     """);
    }

    private static void WriteTelemetryRegistration(CodeWriter code)
    {
        code.Lines("""
                           var telemetry = options.Telemetry;
                           if (telemetry.EnableMetrics || telemetry.EnableTracing)
                           {
                               var enableMetrics = telemetry.EnableMetrics;
                               var enableTracing = telemetry.EnableTracing;
                               var meterName = telemetry.MeterName;
                               var activitySourceName = telemetry.ActivitySourceName;
                               services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton(
                                   typeof(global::Dispatcher.SourceGeneration.DispatcherTelemetry),
                                   _ => new global::Dispatcher.SourceGeneration.DispatcherTelemetry(
                                       enableMetrics,
                                       enableTracing,
                                       meterName,
                                       activitySourceName)));
                               services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(
                                   typeof(global::Dispatcher.SourceGeneration.TelemetryDispatcher),
                                   typeof(global::Dispatcher.SourceGeneration.TelemetryDispatcher),
                                   options.ServiceLifetime));
                   """);
        WriteContractRegistrations(code, "global::Dispatcher.SourceGeneration.TelemetryDispatcher", 12);
        code.Lines("""
                           }
                           else
                           {
                   """);
        WriteContractRegistrations(code, DispatcherType, 12);
        code.Line("        }");
        code.Line();
    }

    private static void WriteContractRegistrations(CodeWriter code, string implementation, int indentation)
    {
        WriteContractRegistration(code, "global::Dispatcher.IDispatcher", implementation, indentation);
        WriteContractRegistration(code, "global::Dispatcher.IQueryDispatcher", implementation, indentation);
        WriteContractRegistration(code, "global::Dispatcher.ICommandDispatcher", implementation, indentation);
        WriteContractRegistration(code, "global::Dispatcher.INotificationDispatcher", implementation, indentation);
    }

    private static void WriteContractRegistration(
        CodeWriter code,
        string contract,
        string implementation,
        int indentation)
    {
        var prefix = new string(' ', indentation);
        code.Line(
            $"{prefix}services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof({contract}), static provider =>");
        code.Line($"{prefix}    provider.GetService(typeof({implementation})) ??");
        code.Line(
            $"{prefix}    throw new global::System.InvalidOperationException(\"Service '{implementation}' is not registered.\"), options.ServiceLifetime));");
    }
}