using System.Text;
using Dispatcher.SourceGeneration.Model;
using Dispatcher.SourceGeneration.Support;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Dispatcher.SourceGeneration.Emission;

internal static class HandlerRegistrationEmitter
{
    internal static void Emit(SourceProductionContext output, GenerationModel generation)
    {
        var className = "GeneratedHandlerServiceCollectionExtensions_" +
                        GeneratedIdentifier.From(generation.AssemblyName);
        var code = new CodeWriter();
        code.Lines("""
                   // <auto-generated />
                   #nullable enable
                   namespace Dispatcher.SourceGeneration;

                   /// <summary>
                   /// Provides registration methods for source-generated handlers in this assembly.
                   /// </summary>
                   """);
        code.Begin($"public static class {className}");
        if (generation.HandlerRegistrationMethod is not null)
        {
            WriteHandlerRegistration(code, generation);
        }

        foreach (var handler in generation.LocalOpenNotificationHandlers)
        {
            WriteOpenHandler(code, handler);
        }

        code.End();
        output.AddSource(className + ".g.cs", SourceText.From(code.ToString(), Encoding.UTF8));
    }

    private static void WriteHandlerRegistration(CodeWriter code, GenerationModel generation)
    {
        var method = generation.HandlerRegistrationMethod!;
        code.Lines($$"""
                     /// <summary>
                     /// Registers the source-generated handlers in this assembly.
                     /// </summary>
                     /// <param name="services">The service collection to add the handlers to.</param>
                     /// <returns>The same service collection so that additional calls can be chained.</returns>
                     /// <exception cref="global::System.ArgumentNullException">
                     /// <paramref name="services"/> is <see langword="null"/>.
                     /// </exception>
                     public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection {{method}}(
                         this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                         => {{method}}(services, static _ => { });

                     /// <summary>
                     /// Registers the source-generated handlers in this assembly using the specified options.
                     /// </summary>
                     /// <param name="services">The service collection to add the handlers to.</param>
                     /// <param name="configure">The delegate that configures handler registration.</param>
                     /// <returns>The same service collection so that additional calls can be chained.</returns>
                     /// <exception cref="global::System.ArgumentNullException">
                     /// <paramref name="services"/> or <paramref name="configure"/> is <see langword="null"/>.
                     /// </exception>
                     public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection {{method}}(
                         this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
                         global::System.Action<global::Dispatcher.DispatcherOptions> configure)
                     """);
        code.Begin("");
        code.Lines("""
                   global::System.ArgumentNullException.ThrowIfNull(services);
                   global::System.ArgumentNullException.ThrowIfNull(configure);
                   var options = new global::Dispatcher.DispatcherOptions();
                   configure(options);
                   """);
        foreach (var handler in generation.LocalHandlers)
        {
            code.Line(RegistrationCall(handler));
        }

        foreach (var handler in generation.LocalOpenNotificationHandlers)
        {
            var names = new OpenHandlerMethodNames(handler);
            code.Line($"RegisterOpenNotificationHandler_{names.Suffix}(services, options.ServiceLifetime);");
        }

        code.Line();
        code.Line("return services;");
        code.End();
    }

    private static string RegistrationCall(HandlerDefinition handler)
    {
        var method = handler.Kind switch
        {
            HandlerKind.Query => "AddQueryHandler",
            HandlerKind.CommandWithResponse or HandlerKind.Command => "AddCommandHandler",
            _ => "AddNotificationHandler"
        };
        var message = CSharpNames.Type(handler.MessageType);
        var implementation = CSharpNames.Type(handler.ImplementationType);
        var arguments = handler.ResponseType is null
            ? $"{message}, {implementation}"
            : $"{message}, {CSharpNames.Type(handler.ResponseType)}, {implementation}";
        return $"global::Dispatcher.ServiceCollectionExtensions.{method}<{arguments}>(services, " +
               "handlerOptions => handlerOptions.ServiceLifetime = options.ServiceLifetime);";
    }

    private static void WriteOpenHandler(CodeWriter code, OpenNotificationHandlerDefinition handler)
    {
        var names = new OpenHandlerMethodNames(handler);
        var parameter = handler.NotificationTypeParameter;
        var typeParameter = parameter.Name;
        var implementation = CSharpNames.Type(handler.ImplementationType);
        var visibility = handler.IsCallableFromOtherAssemblies ? "public" : "internal";

        code.Line();
        code.Lines($$"""
                     /// <summary>
                     /// Registers this generated open notification handler for a concrete notification type.
                     /// </summary>
                     /// <typeparam name="{{typeParameter}}">The concrete notification type.</typeparam>
                     /// <param name="services">The service collection to add the handler to.</param>
                     /// <exception cref="global::System.ArgumentNullException">
                     /// <paramref name="services"/> is <see langword="null"/>.
                     /// </exception>
                     {{visibility}} static void RegisterOpenNotificationHandler_{{names.Suffix}}<{{typeParameter}}>(
                         global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                     """);
        WriteConstraints(code, parameter);
        code.Begin("");
        code.Line("global::System.ArgumentNullException.ThrowIfNull(services);");
        code.Line($"var state = GetOpenNotificationHandlerState_{names.Suffix}(services);");
        code.Begin($"if (!state.NotificationTypes.Add(typeof({typeParameter})))");
        code.Line("return;");
        code.End();
        code.Line();
        code.Line($"global::System.Action<global::Microsoft.Extensions.DependencyInjection.IServiceCollection, " +
                  $"global::Microsoft.Extensions.DependencyInjection.ServiceLifetime> registration = " +
                  $"RegisterClosedOpenNotificationHandler_{names.Suffix}<{typeParameter}>;");
        code.Line("state.Registrations.Add(registration);");
        code.Begin("if (state.IsHandlerRegistered)");
        code.Line("registration(services, state.Lifetime);");
        code.End();
        code.End();

        code.Line();
        code.Lines($$"""
                     /// <summary>
                     /// Registers pending closed routes when a descriptor belongs to this generated handler.
                     /// </summary>
                     /// <param name="descriptor">The service descriptor to inspect.</param>
                     /// <param name="services">The service collection to add closed handlers to.</param>
                     /// <returns><see langword="true"/> when the descriptor belongs to this handler.</returns>
                     public static bool RegisterPendingOpenNotificationHandler_{{names.Suffix}}(
                         global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor descriptor,
                         global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                     """);
        code.Begin("");
        code.Lines("""
                   global::System.ArgumentNullException.ThrowIfNull(descriptor);
                   global::System.ArgumentNullException.ThrowIfNull(services);
                   """);
        code.Begin($"if (descriptor.ImplementationInstance is not OpenNotificationHandlerState_{names.Suffix} state)");
        code.Line("return false;");
        code.End();
        code.Line();
        code.Begin("if (state.IsHandlerRegistered)");
        code.Begin("foreach (var registration in state.Registrations)");
        code.Line("registration(services, state.Lifetime);");
        code.End();
        code.End();
        code.Line();
        code.Line("return true;");
        code.End();

        code.Line();
        code.Lines($$"""
                     /// <summary>
                     /// Identifies the closed service descriptor for this generated notification handler.
                     /// </summary>
                     /// <typeparam name="{{typeParameter}}">The concrete notification type.</typeparam>
                     /// <param name="descriptor">The service descriptor to inspect.</param>
                     /// <returns><see langword="true"/> when the descriptor registers this handler.</returns>
                     {{visibility}} static bool IsOpenNotificationHandler_{{names.Suffix}}<{{typeParameter}}>(
                         global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor descriptor)
                     """);
        WriteConstraints(code, parameter);
        code.Begin("");
        code.Line($"var handlerType = typeof({implementation});");
        code.Lines("""
                   return !descriptor.IsKeyedService &&
                       descriptor.ServiceType == handlerType &&
                       (descriptor.ImplementationType ?? descriptor.ImplementationInstance?.GetType()) == handlerType;
                   """);
        code.End();

        code.Line();
        code.Lines($$"""
                     /// <summary>
                     /// Invokes a generated open notification handler closed over a concrete notification type.
                     /// </summary>
                     /// <typeparam name="{{typeParameter}}">The concrete notification type.</typeparam>
                     /// <param name="serviceProvider">The service provider used to resolve the handler.</param>
                     /// <param name="notification">The notification to handle.</param>
                     /// <param name="cancellationToken">The cancellation token for the operation.</param>
                     /// <returns>A value task that represents the handler invocation.</returns>
                     {{visibility}} static global::System.Threading.Tasks.ValueTask InvokeOpenNotificationHandler_{{names.Suffix}}<{{typeParameter}}>(
                         global::System.IServiceProvider serviceProvider,
                         {{typeParameter}} notification,
                         global::System.Threading.CancellationToken cancellationToken)
                     """);
        WriteConstraints(code, parameter);
        code.Begin("");
        code.Line(
            $"var handler = (global::Dispatcher.INotificationHandler<{typeParameter}>?)serviceProvider.GetService(typeof({implementation})) ??");
        code.Line(
            $"    throw new global::System.InvalidOperationException($\"Service '{{typeof({implementation}).FullName}}' is not registered.\");");
        code.Line("return handler.HandleAsync(notification, cancellationToken);");
        code.End();

        WriteOpenHandlerInfrastructure(code, handler, names, typeParameter, implementation);
    }

    private static void WriteOpenHandlerInfrastructure(
        CodeWriter code,
        OpenNotificationHandlerDefinition handler,
        OpenHandlerMethodNames names,
        string typeParameter,
        string implementation)
    {
        code.Line();
        code.Lines($$"""
                     private static void RegisterOpenNotificationHandler_{{names.Suffix}}(
                         global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
                         global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime)
                     """);
        code.Begin("");
        code.Line($"var state = GetOpenNotificationHandlerState_{names.Suffix}(services);");
        code.Begin("if (state.IsHandlerRegistered)");
        code.Line("return;");
        code.End();
        code.Line();
        code.Lines("""
                   state.IsHandlerRegistered = true;
                   state.Lifetime = lifetime;
                   """);
        code.Begin("foreach (var registration in state.Registrations)");
        code.Line("registration(services, lifetime);");
        code.End();
        code.End();

        code.Line();
        code.Lines($$"""
                     private static void RegisterClosedOpenNotificationHandler_{{names.Suffix}}<{{typeParameter}}>(
                         global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
                         global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime)
                     """);
        WriteConstraints(code, handler.NotificationTypeParameter);
        code.Begin("");
        code.Line($"var handlerType = typeof({implementation});");
        code.Begin("foreach (var descriptor in services)");
        code.Lines("""
                   if (!descriptor.IsKeyedService &&
                       descriptor.ServiceType == handlerType &&
                       (descriptor.ImplementationType ?? descriptor.ImplementationInstance?.GetType()) == handlerType)
                   """);
        code.Begin("");
        code.Line("return;");
        code.End();
        code.End();
        code.Line();
        code.Lines("""
                   services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(
                       handlerType,
                       handlerType,
                       lifetime));
                   """);
        code.End();

        code.Line();
        code.Lines($$"""
                     private static OpenNotificationHandlerState_{{names.Suffix}} GetOpenNotificationHandlerState_{{names.Suffix}}(
                         global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                     """);
        code.Begin("");
        code.Begin("foreach (var descriptor in services)");
        code.Begin($"if (descriptor.ImplementationInstance is OpenNotificationHandlerState_{names.Suffix} state)");
        code.Line("return state;");
        code.End();
        code.End();
        code.Line();
        code.Line($"var created = new OpenNotificationHandlerState_{names.Suffix}();");
        code.Lines($$"""
                     services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton(
                         typeof(OpenNotificationHandlerState_{{names.Suffix}}),
                         created));
                     return created;
                     """);
        code.End();

        code.Line();
        code.Begin($"private sealed class OpenNotificationHandlerState_{names.Suffix}");
        code.Lines("""
                   internal bool IsHandlerRegistered { get; set; }

                   internal global::Microsoft.Extensions.DependencyInjection.ServiceLifetime Lifetime { get; set; }

                   internal global::System.Collections.Generic.HashSet<global::System.Type> NotificationTypes { get; } = [];

                   internal global::System.Collections.Generic.List<global::System.Action<
                       global::Microsoft.Extensions.DependencyInjection.IServiceCollection,
                       global::Microsoft.Extensions.DependencyInjection.ServiceLifetime>> Registrations { get; } = [];
                   """);
        code.End();
    }

    private static void WriteConstraints(CodeWriter code, ITypeParameterSymbol parameter)
    {
        var constraints = new List<string>();
        if (parameter.HasUnmanagedTypeConstraint)
        {
            constraints.Add("unmanaged");
        }
        else if (parameter.HasValueTypeConstraint)
        {
            constraints.Add("struct");
        }
        else if (parameter.HasReferenceTypeConstraint)
        {
            constraints.Add(parameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated
                ? "class?"
                : "class");
        }
        else if (parameter.HasNotNullConstraint)
        {
            constraints.Add("notnull");
        }

        constraints.AddRange(parameter.ConstraintTypes.Select(CSharpNames.Type));
        if (parameter.HasConstructorConstraint)
        {
            constraints.Add("new()");
        }

        if (constraints.Count > 0)
        {
            code.Line($"    where {parameter.Name} : {string.Join(", ", constraints)}");
        }
    }
}