using System.Collections.Immutable;
using System.Text;
using Dispatcher.SourceGeneration.Model;
using Dispatcher.SourceGeneration.Support;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Dispatcher.SourceGeneration.Emission;

internal static class PipelineBehaviorRegistrationEmitter
{
    internal static void Emit(SourceProductionContext output, GenerationModel generation)
    {
        var requests = generation.Routes
            .Where(static route => route.Handler is not null && route.Handler.Kind != HandlerKind.Notification)
            .Select(route => new RequestShape(
                route.Handler!.MessageType,
                route.Handler.Kind == HandlerKind.Command ? generation.UnitType! : route.Handler.ResponseType!))
            .GroupBy(
                static request => CSharpNames.Type(request.Request) + "|" + CSharpNames.Type(request.Response),
                StringComparer.Ordinal)
            .Select(static group => group.First())
            .ToArray();
        var code = new CodeWriter();
        code.Lines("""
            // <auto-generated />
            #nullable enable
            namespace Dispatcher.SourceGeneration;

            /// <summary>
            /// Provides source-generated registration methods for open generic pipeline behaviors.
            /// </summary>
            public static class GeneratedPipelineBehaviorServiceCollectionExtensions
            {
                /// <summary>
                /// Registers a pipeline behavior discovered by the Dispatcher generator.
                /// </summary>
                /// <param name="services">The service collection to add the behavior to.</param>
                /// <param name="behaviorType">The open generic behavior type to register.</param>
                /// <returns>The same service collection so that additional calls can be chained.</returns>
                /// <exception cref="global::System.ArgumentNullException">
                /// <paramref name="services"/> or <paramref name="behaviorType"/> is <see langword="null"/>.
                /// </exception>
                /// <exception cref="global::System.ArgumentException">
                /// <paramref name="behaviorType"/> was not discovered by the Dispatcher generator.
                /// </exception>
                public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddPipelineBehavior(
                    this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
                    global::System.Type behaviorType)
                    => AddPipelineBehavior(services, behaviorType, static _ => { });

                /// <summary>
                /// Registers a pipeline behavior discovered by the Dispatcher generator using the specified options.
                /// </summary>
                /// <param name="services">The service collection to add the behavior to.</param>
                /// <param name="behaviorType">The open generic behavior type to register.</param>
                /// <param name="configure">The delegate that configures behavior registration.</param>
                /// <returns>The same service collection so that additional calls can be chained.</returns>
                /// <exception cref="global::System.ArgumentNullException">
                /// <paramref name="services"/>, <paramref name="behaviorType"/>, or <paramref name="configure"/> is <see langword="null"/>.
                /// </exception>
                /// <exception cref="global::System.ArgumentException">
                /// <paramref name="behaviorType"/> was not discovered by the Dispatcher generator.
                /// </exception>
                public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddPipelineBehavior(
                    this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
                    global::System.Type behaviorType,
                    global::System.Action<global::Dispatcher.DispatcherOptions> configure)
                {
                    global::System.ArgumentNullException.ThrowIfNull(services);
                    global::System.ArgumentNullException.ThrowIfNull(behaviorType);
                    global::System.ArgumentNullException.ThrowIfNull(configure);
                    var options = new global::Dispatcher.DispatcherOptions();
                    configure(options);
            """);
        foreach (var behavior in generation.PipelineBehaviors)
        {
            WriteBehaviorRegistration(code, behavior, requests);
        }

        code.Lines("""

                    throw new global::System.ArgumentException(
                        $"Pipeline behavior '{behaviorType.FullName}' was not discovered by the Dispatcher generator.",
                        nameof(behaviorType));
                }
            }
            """);
        output.AddSource(
            "GeneratedPipelineBehaviorServiceCollectionExtensions.g.cs",
            SourceText.From(code.ToString(), Encoding.UTF8));
    }

    private static void WriteBehaviorRegistration(
        CodeWriter code,
        INamedTypeSymbol behavior,
        IEnumerable<RequestShape> requests)
    {
        code.Line();
        code.Line($"        if (behaviorType == typeof({CSharpNames.Type(behavior.ConstructUnboundGenericType())}))");
        code.Line("        {");
        foreach (var request in requests)
        {
            if (!CanClose(behavior, request))
            {
                continue;
            }

            var requestType = CSharpNames.Type(request.Request);
            var responseType = CSharpNames.Type(request.Response);
            var implementation = CSharpNames.Type(behavior.Construct(request.Request, request.Response));
            code.Line($"            global::Dispatcher.ServiceCollectionExtensions.AddPipelineBehavior<{requestType}, {responseType}, {implementation}>(services, behaviorOptions => behaviorOptions.ServiceLifetime = options.ServiceLifetime);");
        }

        code.Line("            return services;");
        code.Line("        }");
    }

    private static bool CanClose(INamedTypeSymbol behavior, RequestShape request)
    {
        ITypeSymbol[] arguments = [request.Request, request.Response];
        for (var index = 0; index < behavior.TypeParameters.Length; index++)
        {
            var parameter = behavior.TypeParameters[index];
            var argument = arguments[index];
            if (parameter.HasUnmanagedTypeConstraint && !argument.IsUnmanagedType ||
                parameter.HasReferenceTypeConstraint && !argument.IsReferenceType ||
                parameter.HasValueTypeConstraint && !argument.IsValueType ||
                parameter.HasConstructorConstraint && !HasPublicParameterlessConstructor(argument))
            {
                return false;
            }

            foreach (var constraint in parameter.ConstraintTypes)
            {
                var closedConstraint = SubstituteTypeParameters(constraint, behavior.TypeParameters, arguments);
                if (!SatisfiesTypeConstraint(argument, closedConstraint))
                {
                    return false;
                }
            }
        }

        return true;
    }

    private static bool HasPublicParameterlessConstructor(ITypeSymbol type) =>
        type is not INamedTypeSymbol namedType ||
        namedType.InstanceConstructors.Any(static constructor =>
            constructor.Parameters.IsEmpty && constructor.DeclaredAccessibility == Accessibility.Public);

    private static ITypeSymbol SubstituteTypeParameters(
        ITypeSymbol type,
        ImmutableArray<ITypeParameterSymbol> parameters,
        IReadOnlyList<ITypeSymbol> arguments)
    {
        if (type is ITypeParameterSymbol parameter)
        {
            var index = parameters.IndexOf(parameter, SymbolEqualityComparer.Default);
            return index >= 0 ? arguments[index] : type;
        }

        if (type is not INamedTypeSymbol namedType || !namedType.IsGenericType)
        {
            return type;
        }

        return namedType.OriginalDefinition.Construct(namedType.TypeArguments
            .Select(argument => SubstituteTypeParameters(argument, parameters, arguments))
            .ToArray());
    }

    private static bool SatisfiesTypeConstraint(ITypeSymbol argument, ITypeSymbol constraint)
    {
        if (SymbolEqualityComparer.Default.Equals(argument, constraint))
        {
            return true;
        }

        if (argument is not INamedTypeSymbol namedArgument)
        {
            return false;
        }

        if (namedArgument.AllInterfaces.Any(@interface =>
                SymbolEqualityComparer.Default.Equals(@interface, constraint)))
        {
            return true;
        }

        for (var baseType = namedArgument.BaseType; baseType is not null; baseType = baseType.BaseType)
        {
            if (SymbolEqualityComparer.Default.Equals(baseType, constraint))
            {
                return true;
            }
        }

        return false;
    }

    private sealed class RequestShape(ITypeSymbol request, ITypeSymbol response)
    {
        internal ITypeSymbol Request { get; } = request;
        internal ITypeSymbol Response { get; } = response;
    }
}