namespace Dispatcher.SourceGeneration.Support;

internal static class GeneratedAttributes
{
    internal const string HandlerRegistration = """
        // <auto-generated />
        #nullable enable

        namespace Dispatcher.SourceGeneration;

        [global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]
        internal sealed class GenerateDispatcherHandlersAttribute : global::System.Attribute
        {
            public GenerateDispatcherHandlersAttribute(string methodName)
            {
                MethodName = methodName;
            }

            public string MethodName { get; }
        }
        """;

    internal const string DispatcherRegistration = """
        // <auto-generated />
        #nullable enable

        namespace Dispatcher.SourceGeneration;

        [global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]
        internal sealed class GenerateDispatcherAttribute : global::System.Attribute
        {
            public GenerateDispatcherAttribute(string methodName)
            {
                MethodName = methodName;
            }

            public string MethodName { get; }
        }
        """;
}