<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Dispatcher.SampleApi.Contracts/Dispatcher.SampleApi.Contracts.csproj" />
    <ProjectReference Include="../Dispatcher.SampleApi.Modules.Orders/Dispatcher.SampleApi.Modules.Orders.csproj" />
    <ProjectReference Include="../Dispatcher.SampleApi.Modules.Stock/Dispatcher.SampleApi.Modules.Stock.csproj" />
    <ProjectReference Include="../../../src/Dispatcher.DependencyInjection/Dispatcher.DependencyInjection.csproj" />
    <PackageReference Include="FluentValidation" />
  </ItemGroup>
</Project>
